import { defineConfig, Options } from 'tsup';

export default defineConfig((options: Options) => ({
  treeshake: true,
  splitting: true,
  entry: [
    'src/index.ts',
    'src/hooks/index.ts',
    'src/provider/index.ts',
    'src/bridges/index.ts',
    'src/actions/index.ts',
    'src/server/index.ts',
    'src/federation/index.ts',
  ],
  format: ['esm', 'cjs'],
  dts: true,
  minify: true,
  clean: true,
  external: [
    'react',
    'react-dom',
    'next',
    'mobx',
    '@copilotkit/react-core',
    '@copilotkit/react-core/v2',
    '@copilotkit/react-ui',
    '@copilotkit/runtime',
    '@copilotkit/runtime/v2',
    '@ag-ui/client',
    '@ag-ui/core',
    '@ag-ui/encoder',
    '@ag-ui/proto',
    'hono',
    'hono/vercel',
  ],
  ...options,
}));
