export declare const animateFromRight: string
export declare const animateFromTop: string
export declare const chatContent: string
export declare const chatMessage: string
export declare const chatMessageAvatar: string
export declare const chatMessageContent: string
export declare const chatMessages: string
export declare const chatWindow: string
export declare const chatWindowInput: string
export declare const dot: string
export declare const flexinessRoot: string
export declare const fromRight: string
export declare const fromTop: string
export declare const isMe: string
export declare const isPartner: string
export declare const isScrollable: string
export declare const isWaiting: string
export declare const placeHolderShimmer: string
export declare const spinAround: string
export declare const wave: string
