export declare const animateFromRight: string
export declare const animateFromTop: string
export declare const box: string
export declare const boxContent: string
export declare const flexinessRoot: string
export declare const fromRight: string
export declare const fromTop: string
export declare const isActive: string
export declare const isLarge: string
export declare const isMedium: string
export declare const isSmall: string
export declare const modal: string
export declare const modalBackground: string
export declare const modalClose: string
export declare const modalContent: string
export declare const modalTitle: string
export declare const placeHolderShimmer: string
export declare const spinAround: string
