export declare const control: string
export declare const fa: string
export declare const flexinessRoot: string
export declare const isActive: string
export declare const isAdmin: string
export declare const isCobalt: string
export declare const isDanger: string
export declare const isDebug: string
export declare const isFlexGreen: string
export declare const isFlexOrange: string
export declare const isFlexPink: string
export declare const isFlexPurple: string
export declare const isInfo: string
export declare const isPrimary: string
export declare const isQuaternary: string
export declare const isSecondary: string
export declare const isSuccess: string
export declare const isTertiary: string
export declare const isTertiaryDark: string
export declare const isTertiaryLight: string
export declare const isWarning: string
export declare const isWhite: string
export declare const isWrapped: string
export declare const panel: string
export declare const panelBlock: string
export declare const panelHeading: string
export declare const panelIcon: string
export declare const panelList: string
export declare const panelTabs: string
