export declare const animateFromRight: string
export declare const animateFromTop: string
export declare const centimes: string
export declare const cents: string
export declare const flexinessRoot: string
export declare const fromRight: string
export declare const fromTop: string
export declare const hasDescription: string
export declare const icon: string
export declare const is1: string
export declare const is2: string
export declare const is3: string
export declare const is4: string
export declare const is5: string
export declare const is6: string
export declare const isAdmin: string
export declare const isHuge: string
export declare const isInlined: string
export declare const isInverted: string
export declare const isMainPrice: string
export declare const isStriked: string
export declare const main: string
export declare const period: string
export declare const periode: string
export declare const placeHolderShimmer: string
export declare const price: string
export declare const priceDetails: string
export declare const spinAround: string
