export declare const animateFromRight: string
export declare const animateFromTop: string
export declare const arrow: string
export declare const close: string
export declare const flexinessRoot: string
export declare const fromRight: string
export declare const fromTop: string
export declare const hasIconLeft: string
export declare const hasIconRight: string
export declare const icon: string
export declare const isActive: string
export declare const isBottom: string
export declare const isFourFifths: string
export declare const isLeft: string
export declare const isOneFifth: string
export declare const isOneQuarter: string
export declare const isOneThird: string
export declare const isRight: string
export declare const isThreeFifths: string
export declare const isThreeQuarters: string
export declare const isTwoFifths: string
export declare const isTwoThirds: string
export declare const placeHolderShimmer: string
export declare const productTour: string
export declare const productTourTargetActive: string
export declare const spinAround: string
