export declare const animateFromRight: string
export declare const animateFromTop: string
export declare const description: string
export declare const flexinessRoot: string
export declare const fromRight: string
export declare const fromTop: string
export declare const hasDescription: string
export declare const label: string
export declare const pie: string
export declare const placeHolderShimmer: string
export declare const progress0: string
export declare const progress1: string
export declare const progress10: string
export declare const progress100: string
export declare const progress11: string
export declare const progress12: string
export declare const progress13: string
export declare const progress14: string
export declare const progress15: string
export declare const progress16: string
export declare const progress17: string
export declare const progress18: string
export declare const progress19: string
export declare const progress2: string
export declare const progress20: string
export declare const progress21: string
export declare const progress22: string
export declare const progress23: string
export declare const progress24: string
export declare const progress25: string
export declare const progress26: string
export declare const progress27: string
export declare const progress28: string
export declare const progress29: string
export declare const progress3: string
export declare const progress30: string
export declare const progress31: string
export declare const progress32: string
export declare const progress33: string
export declare const progress34: string
export declare const progress35: string
export declare const progress36: string
export declare const progress37: string
export declare const progress38: string
export declare const progress39: string
export declare const progress4: string
export declare const progress40: string
export declare const progress41: string
export declare const progress42: string
export declare const progress43: string
export declare const progress44: string
export declare const progress45: string
export declare const progress46: string
export declare const progress47: string
export declare const progress48: string
export declare const progress49: string
export declare const progress5: string
export declare const progress50: string
export declare const progress51: string
export declare const progress52: string
export declare const progress53: string
export declare const progress54: string
export declare const progress55: string
export declare const progress56: string
export declare const progress57: string
export declare const progress58: string
export declare const progress59: string
export declare const progress6: string
export declare const progress60: string
export declare const progress61: string
export declare const progress62: string
export declare const progress63: string
export declare const progress64: string
export declare const progress65: string
export declare const progress66: string
export declare const progress67: string
export declare const progress68: string
export declare const progress69: string
export declare const progress7: string
export declare const progress70: string
export declare const progress71: string
export declare const progress72: string
export declare const progress73: string
export declare const progress74: string
export declare const progress75: string
export declare const progress76: string
export declare const progress77: string
export declare const progress78: string
export declare const progress79: string
export declare const progress8: string
export declare const progress80: string
export declare const progress81: string
export declare const progress82: string
export declare const progress83: string
export declare const progress84: string
export declare const progress85: string
export declare const progress86: string
export declare const progress87: string
export declare const progress88: string
export declare const progress89: string
export declare const progress9: string
export declare const progress90: string
export declare const progress91: string
export declare const progress92: string
export declare const progress93: string
export declare const progress94: string
export declare const progress95: string
export declare const progress96: string
export declare const progress97: string
export declare const progress98: string
export declare const progress99: string
export declare const radialProgressBar: string
export declare const radialProgressBars: string
export declare const spinAround: string
