export declare const animateFromRight: string
export declare const animateFromTop: string
export declare const button: string
export declare const control: string
export declare const field: string
export declare const flexinessRoot: string
export declare const flexiUiArrowRightR: string
export declare const fromRight: string
export declare const fromTop: string
export declare const hasLongCta: string
export declare const image: string
export declare const isAdmin: string
export declare const isCheckradio: string
export declare const isDisabled: string
export declare const isIllustratedMobile: string
export declare const isMutuallyExclusive: string
export declare const isRounded: string
export declare const isSelectLine: string
export declare const isText: string
export declare const isTransparent: string
export declare const placeHolderShimmer: string
export declare const slice: string
export declare const sliceBody: string
export declare const sliceCallToAction: string
export declare const sliceContent: string
export declare const sliceGroup: string
export declare const sliceIcon: string
export declare const sliceImage: string
export declare const slices: string
export declare const sliceSelect: string
export declare const spinAround: string
export declare const title: string
