export declare const animateFromRight: string
export declare const animateFromTop: string
export declare const flexinessRoot: string
export declare const fromRight: string
export declare const fromTop: string
export declare const isActive: string
export declare const isCurrent: string
export declare const isDone: string
export declare const isHighlighted: string
export declare const isValidated: string
export declare const placeHolderShimmer: string
export declare const spinAround: string
export declare const step: string
export declare const stepper: string
