export declare const animateFromRight: string
export declare const animateFromTop: string
export declare const flexinessRoot: string
export declare const fromRight: string
export declare const fromTop: string
export declare const isActive: string
export declare const isCentered: string
export declare const isClipped: string
export declare const isFullwidth: string
export declare const isRight: string
export declare const placeHolderShimmer: string
export declare const spinAround: string
export declare const tabs: string
