export declare const animateFromRight: string
export declare const animateFromTop: string
export declare const box: string
export declare const boxHeader: string
export declare const button: string
export declare const column: string
export declare const container: string
export declare const dl: string
export declare const field: string
export declare const flexinessRoot: string
export declare const fromRight: string
export declare const fromTop: string
export declare const hasBackgroundAdmin: string
export declare const hasBackgroundCobalt: string
export declare const hasBackgroundDanger: string
export declare const hasBackgroundDebug: string
export declare const hasBackgroundFlexGreen: string
export declare const hasBackgroundFlexOrange: string
export declare const hasBackgroundFlexPink: string
export declare const hasBackgroundFlexPurple: string
export declare const hasBackgroundGrey: string
export declare const hasBackgroundGreyDark: string
export declare const hasBackgroundGreyLight: string
export declare const hasBackgroundGreyLighter: string
export declare const hasBackgroundInfo: string
export declare const hasBackgroundPrimary: string
export declare const hasBackgroundQuaternary: string
export declare const hasBackgroundSecondary: string
export declare const hasBackgroundSuccess: string
export declare const hasBackgroundTertiary: string
export declare const hasBackgroundTertiaryDark: string
export declare const hasBackgroundTertiaryLight: string
export declare const hasBackgroundWarning: string
export declare const hasBackgroundWhite: string
export declare const hasBorderRadius: string
export declare const hasBorderRadiusLarge: string
export declare const hasBorderRadiusSmall: string
export declare const hasInheritedColor: string
export declare const hasOverlay: string
export declare const hasTextAdmin: string
export declare const hasTextAdminInvert: string
export declare const hasTextCentered: string
export declare const hasTextCenteredDesktop: string
export declare const hasTextCenteredDesktopOnly: string
export declare const hasTextCenteredFullhd: string
export declare const hasTextCenteredMobile: string
export declare const hasTextCenteredTablet: string
export declare const hasTextCenteredTabletOnly: string
export declare const hasTextCenteredTouch: string
export declare const hasTextCenteredWidescreen: string
export declare const hasTextCenteredWidescreenOnly: string
export declare const hasTextCobalt: string
export declare const hasTextCobaltInvert: string
export declare const hasTextDanger: string
export declare const hasTextDangerInvert: string
export declare const hasTextDebug: string
export declare const hasTextDebugInvert: string
export declare const hasTextFlexGreen: string
export declare const hasTextFlexGreenInvert: string
export declare const hasTextFlexOrange: string
export declare const hasTextFlexOrangeInvert: string
export declare const hasTextFlexPink: string
export declare const hasTextFlexPinkInvert: string
export declare const hasTextFlexPurple: string
export declare const hasTextFlexPurpleInvert: string
export declare const hasTextGrey: string
export declare const hasTextGreyDark: string
export declare const hasTextGreyLight: string
export declare const hasTextGreyLighter: string
export declare const hasTextInfo: string
export declare const hasTextInfoInvert: string
export declare const hasTextJustified: string
export declare const hasTextJustifiedDesktop: string
export declare const hasTextJustifiedDesktopOnly: string
export declare const hasTextJustifiedFullhd: string
export declare const hasTextJustifiedMobile: string
export declare const hasTextJustifiedTablet: string
export declare const hasTextJustifiedTabletOnly: string
export declare const hasTextJustifiedTouch: string
export declare const hasTextJustifiedWidescreen: string
export declare const hasTextJustifiedWidescreenOnly: string
export declare const hasTextLeft: string
export declare const hasTextLeftDesktop: string
export declare const hasTextLeftDesktopOnly: string
export declare const hasTextLeftFullhd: string
export declare const hasTextLeftMobile: string
export declare const hasTextLeftTablet: string
export declare const hasTextLeftTabletOnly: string
export declare const hasTextLeftTouch: string
export declare const hasTextLeftWidescreen: string
export declare const hasTextLeftWidescreenOnly: string
export declare const hasTextPrimary: string
export declare const hasTextPrimaryInvert: string
export declare const hasTextQuaternary: string
export declare const hasTextQuaternaryInvert: string
export declare const hasTextRight: string
export declare const hasTextRightDesktop: string
export declare const hasTextRightDesktopOnly: string
export declare const hasTextRightFullhd: string
export declare const hasTextRightMobile: string
export declare const hasTextRightTablet: string
export declare const hasTextRightTabletOnly: string
export declare const hasTextRightTouch: string
export declare const hasTextRightWidescreen: string
export declare const hasTextRightWidescreenOnly: string
export declare const hasTextSecondary: string
export declare const hasTextSecondaryInvert: string
export declare const hasTextSuccess: string
export declare const hasTextSuccessInvert: string
export declare const hasTextTertiary: string
export declare const hasTextTertiaryDark: string
export declare const hasTextTertiaryDarkInvert: string
export declare const hasTextTertiaryInvert: string
export declare const hasTextTertiaryLight: string
export declare const hasTextTertiaryLightInvert: string
export declare const hasTextWarning: string
export declare const hasTextWarningInvert: string
export declare const hasTextWeightBold: string
export declare const hasTextWeightExtrabold: string
export declare const hasTextWeightLight: string
export declare const hasTextWeightMedium: string
export declare const hasTextWeightNormal: string
export declare const hasTextWeightSemibold: string
export declare const hasTextWhite: string
export declare const hasTextWhiteInvert: string
export declare const hasVariant: string
export declare const hasWireframes: string
export declare const heroBody: string
export declare const icon: string
export declare const iconList: string
export declare const input: string
export declare const isAdmin: string
export declare const isAlignContentBaseline: string
export declare const isAlignContentCenter: string
export declare const isAlignContentEnd: string
export declare const isAlignContentFlexEnd: string
export declare const isAlignContentFlexStart: string
export declare const isAlignContentSpaceAround: string
export declare const isAlignContentSpaceBetween: string
export declare const isAlignContentSpaceEvenly: string
export declare const isAlignContentStart: string
export declare const isAlignContentStretch: string
export declare const isAlignItemsBaseline: string
export declare const isAlignItemsCenter: string
export declare const isAlignItemsEnd: string
export declare const isAlignItemsFlexEnd: string
export declare const isAlignItemsFlexStart: string
export declare const isAlignItemsSelfEnd: string
export declare const isAlignItemsSelfStart: string
export declare const isAlignItemsStart: string
export declare const isAlignItemsStretch: string
export declare const isAlignSelfAuto: string
export declare const isAlignSelfBaseline: string
export declare const isAlignSelfCenter: string
export declare const isAlignSelfFlexEnd: string
export declare const isAlignSelfFlexStart: string
export declare const isAlignSelfStretch: string
export declare const isAlternate: string
export declare const isBlock: string
export declare const isBlockDesktop: string
export declare const isBlockDesktopOnly: string
export declare const isBlockFullhd: string
export declare const isBlockMobile: string
export declare const isBlockTablet: string
export declare const isBlockTabletOnly: string
export declare const isBlockTouch: string
export declare const isBlockWidescreen: string
export declare const isBlockWidescreenOnly: string
export declare const isBordered: string
export declare const isCapitalized: string
export declare const isCenteredDesktop: string
export declare const isCenteredMobile: string
export declare const isCenteredTablet: string
export declare const isCheckradio: string
export declare const isClearfix: string
export declare const isClipped: string
export declare const isFlex: string
export declare const isFlexDesktop: string
export declare const isFlexDesktopOnly: string
export declare const isFlexDirectionColumn: string
export declare const isFlexDirectionColumnReverse: string
export declare const isFlexDirectionRow: string
export declare const isFlexDirectionRowReverse: string
export declare const isFlexFullhd: string
export declare const isFlexGrow0: string
export declare const isFlexGrow1: string
export declare const isFlexGrow2: string
export declare const isFlexGrow3: string
export declare const isFlexGrow4: string
export declare const isFlexGrow5: string
export declare const isFlexMobile: string
export declare const isFlexShrink0: string
export declare const isFlexShrink1: string
export declare const isFlexShrink2: string
export declare const isFlexShrink3: string
export declare const isFlexShrink4: string
export declare const isFlexShrink5: string
export declare const isFlexTablet: string
export declare const isFlexTabletOnly: string
export declare const isFlexTouch: string
export declare const isFlexWidescreen: string
export declare const isFlexWidescreenOnly: string
export declare const isFlexWrapNowrap: string
export declare const isFlexWrapWrap: string
export declare const isFlexWrapWrapReverse: string
export declare const isFullheight: string
export declare const isFullwidth: string
export declare const isFullwidthMobile: string
export declare const isGap1: string
export declare const isGap2: string
export declare const isGap3: string
export declare const isGap4: string
export declare const isGap5: string
export declare const isGap6: string
export declare const isGap7: string
export declare const isHidden: string
export declare const isHiddenDesktop: string
export declare const isHiddenDesktopOnly: string
export declare const isHiddenFullhd: string
export declare const isHiddenMobile: string
export declare const isHiddenTablet: string
export declare const isHiddenTabletOnly: string
export declare const isHiddenTouch: string
export declare const isHiddenWidescreen: string
export declare const isHiddenWidescreenOnly: string
export declare const isInline: string
export declare const isInlineBlock: string
export declare const isInlineBlockDesktop: string
export declare const isInlineBlockDesktopOnly: string
export declare const isInlineBlockFullhd: string
export declare const isInlineBlockMobile: string
export declare const isInlineBlockTablet: string
export declare const isInlineBlockTabletOnly: string
export declare const isInlineBlockTouch: string
export declare const isInlineBlockWidescreen: string
export declare const isInlineBlockWidescreenOnly: string
export declare const isInlineDesktop: string
export declare const isInlineDesktopOnly: string
export declare const isInlineFlex: string
export declare const isInlineFlexDesktop: string
export declare const isInlineFlexDesktopOnly: string
export declare const isInlineFlexFullhd: string
export declare const isInlineFlexMobile: string
export declare const isInlineFlexTablet: string
export declare const isInlineFlexTabletOnly: string
export declare const isInlineFlexTouch: string
export declare const isInlineFlexWidescreen: string
export declare const isInlineFlexWidescreenOnly: string
export declare const isInlineFullhd: string
export declare const isInlineMobile: string
export declare const isInlineTablet: string
export declare const isInlineTabletOnly: string
export declare const isInlineTouch: string
export declare const isInlineWidescreen: string
export declare const isInlineWidescreenOnly: string
export declare const isInvisible: string
export declare const isInvisibleDesktop: string
export declare const isInvisibleDesktopOnly: string
export declare const isInvisibleFullhd: string
export declare const isInvisibleMobile: string
export declare const isInvisibleTablet: string
export declare const isInvisibleTabletOnly: string
export declare const isInvisibleTouch: string
export declare const isInvisibleWidescreen: string
export declare const isInvisibleWidescreenOnly: string
export declare const isItalic: string
export declare const isJustifiedCenter: string
export declare const isJustifiedCenterDesktop: string
export declare const isJustifiedCenterDesktopOnly: string
export declare const isJustifiedCenterFullhd: string
export declare const isJustifiedCenterMobile: string
export declare const isJustifiedCenterTablet: string
export declare const isJustifiedCenterTabletOnly: string
export declare const isJustifiedCenterTouch: string
export declare const isJustifiedCenterWidescreen: string
export declare const isJustifiedCenterWidescreenOnly: string
export declare const isJustifiedEnd: string
export declare const isJustifiedEndDesktop: string
export declare const isJustifiedEndDesktopOnly: string
export declare const isJustifiedEndFullhd: string
export declare const isJustifiedEndMobile: string
export declare const isJustifiedEndTablet: string
export declare const isJustifiedEndTabletOnly: string
export declare const isJustifiedEndTouch: string
export declare const isJustifiedEndWidescreen: string
export declare const isJustifiedEndWidescreenOnly: string
export declare const isJustifiedStart: string
export declare const isJustifiedStartDesktop: string
export declare const isJustifiedStartDesktopOnly: string
export declare const isJustifiedStartFullhd: string
export declare const isJustifiedStartMobile: string
export declare const isJustifiedStartTablet: string
export declare const isJustifiedStartTabletOnly: string
export declare const isJustifiedStartTouch: string
export declare const isJustifiedStartWidescreen: string
export declare const isJustifiedStartWidescreenOnly: string
export declare const isJustifyContentCenter: string
export declare const isJustifyContentEnd: string
export declare const isJustifyContentFlexEnd: string
export declare const isJustifyContentFlexStart: string
export declare const isJustifyContentLeft: string
export declare const isJustifyContentRight: string
export declare const isJustifyContentSpaceAround: string
export declare const isJustifyContentSpaceBetween: string
export declare const isJustifyContentSpaceEvenly: string
export declare const isJustifyContentStart: string
export declare const isLoaded: string
export declare const isLoading: string
export declare const isLowercase: string
export declare const isMarginless: string
export declare const isMultiline: string
export declare const isOverlay: string
export declare const isPaddingless: string
export declare const isPulledLeft: string
export declare const isPulledRight: string
export declare const isRadiusless: string
export declare const isRounded: string
export declare const isShadowless: string
export declare const isSize1: string
export declare const isSize1Desktop: string
export declare const isSize1Fullhd: string
export declare const isSize1Mobile: string
export declare const isSize1Tablet: string
export declare const isSize1Touch: string
export declare const isSize1Widescreen: string
export declare const isSize2: string
export declare const isSize2Desktop: string
export declare const isSize2Fullhd: string
export declare const isSize2Mobile: string
export declare const isSize2Tablet: string
export declare const isSize2Touch: string
export declare const isSize2Widescreen: string
export declare const isSize3: string
export declare const isSize3Desktop: string
export declare const isSize3Fullhd: string
export declare const isSize3Mobile: string
export declare const isSize3Tablet: string
export declare const isSize3Touch: string
export declare const isSize3Widescreen: string
export declare const isSize4: string
export declare const isSize4Desktop: string
export declare const isSize4Fullhd: string
export declare const isSize4Mobile: string
export declare const isSize4Tablet: string
export declare const isSize4Touch: string
export declare const isSize4Widescreen: string
export declare const isSize5: string
export declare const isSize5Desktop: string
export declare const isSize5Fullhd: string
export declare const isSize5Mobile: string
export declare const isSize5Tablet: string
export declare const isSize5Touch: string
export declare const isSize5Widescreen: string
export declare const isSize6: string
export declare const isSize6Desktop: string
export declare const isSize6Fullhd: string
export declare const isSize6Mobile: string
export declare const isSize6Tablet: string
export declare const isSize6Touch: string
export declare const isSize6Widescreen: string
export declare const isSize7: string
export declare const isSize7Desktop: string
export declare const isSize7Fullhd: string
export declare const isSize7Mobile: string
export declare const isSize7Tablet: string
export declare const isSize7Touch: string
export declare const isSize7Widescreen: string
export declare const isSize8: string
export declare const isSize8Desktop: string
export declare const isSize8Fullhd: string
export declare const isSize8Mobile: string
export declare const isSize8Tablet: string
export declare const isSize8Touch: string
export declare const isSize8Widescreen: string
export declare const isUnderline: string
export declare const isUnselectable: string
export declare const isUppercase: string
export declare const isVcentered: string
export declare const isVcenteredDesktop: string
export declare const isVcenteredMobile: string
export declare const isVcenteredTablet: string
export declare const isWireframe: string
export declare const loadingPulse: string
export declare const mainContent: string
export declare const paragraph: string
export declare const placeHolderShimmer: string
export declare const section: string
export declare const spinAround: string
export declare const suptitle: string
export declare const text: string
export declare const title: string
