export declare const animateFromRight: string
export declare const animateFromTop: string
export declare const field: string
export declare const flexinessRoot: string
export declare const fromRight: string
export declare const fromTop: string
export declare const icon: string
export declare const input: string
export declare const isCheckradio: string
export declare const isLoaded: string
export declare const isLoading: string
export declare const loadingPulse: string
export declare const placeHolderShimmer: string
export declare const spinAround: string
export declare const suptitle: string
