packages:
  - "apps/**"
  - "!apps/gateway/.next/standalone/**"
  - "!apps/gateway/amplify/**"
  - "packages/**"
hoistPattern:
  - "*eslint*"
  - "*prettier*"
  - "@flexiness/*"
  - "@flex-design-system/*"
  - "gateway"
  - "!*aws-*"
allowBuilds:
  "@parcel/watcher": false
  "@scarf/scarf": false
  core-js: false
  cypress: false
  esbuild: false
  protobufjs: false
  sharp: false
  ttf2woff2: false
  unrs-resolver: false
