packages:
  - 'apps/**'
  - '!apps/gateway/.next/standalone/**'
  - '!apps/gateway/amplify/**'
  - 'packages/**'

hoistPattern:
  - '*eslint*'
  - '*prettier*'
  - '@flexiness/*'
  - '@flex-design-system/*'
  - 'gateway'

# ignoredBuiltDependencies:
  # - '@rspack/binding'
  #   - fsevents
  #   - sharp
  #   - '@parcel/watcher'
  #   - core-js
  #   - cypress
  #   - esbuild
  #   - sharp
  #   - ttf2woff2
  #   - unrs-resolver
