export type Styles = {
  animateFromRight: string;
  animateFromTop: string;
  box: string;
  flexinessRoot: string;
  fromRight: string;
  fromTop: string;
  isAdmin: string;
  isBodyHeader: string;
  isBordered: string;
  isBorderedBoxMobileGrey: string;
  isBorderedBoxMobilePurple: string;
  isBorderedBoxMobileSecondary: string;
  isCobalt: string;
  isCompact: string;
  isComparative: string;
  isDanger: string;
  isDataCellResponsiveHelper: string;
  isDebug: string;
  isExpandable: string;
  isExpanded: string;
  isExpansion: string;
  isFlexGreen: string;
  isFlexOrange: string;
  isFlexPink: string;
  isFlexPurple: string;
  isFullwidth: string;
  isGridDisplayGridMobile: string;
  isHoverable: string;
  isInfo: string;
  isLarge: string;
  isNarrow: string;
  isNotBorderedMobile: string;
  isPrimary: string;
  isQuaternary: string;
  isSecondary: string;
  isSelected: string;
  isStriped: string;
  isSuccess: string;
  isTableStackedRowMobile: string;
  isTertiary: string;
  isTertiaryDark: string;
  isTertiaryLight: string;
  isVcentered: string;
  isWarning: string;
  isWhite: string;
  placeHolderShimmer: string;
  spinAround: string;
  subtable: string;
  table: string;
  tableContainer: string;
  text: string;
  title: string;
  toggle: string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
