export declare const accordion: string
export declare const accordionBody: string
export declare const accordionContent: string
export declare const accordionHeader: string
export declare const accordions: string
export declare const accordionTitle: string
export declare const active: string
export declare const animateFromRight: string
export declare const animateFromTop: string
export declare const arrow: string
export declare const asideMenuList: string
export declare const badge: string
export declare const badgeAndText: string
export declare const bellbounce: string
export declare const bellring: string
export declare const bgConnected: string
export declare const bLazy: string
export declare const bLoaded: string
export declare const block: string
export declare const body: string
export declare const box: string
export declare const boxContent: string
export declare const boxFooter: string
export declare const boxHeader: string
export declare const breadcrumb: string
export declare const burgerMenu: string
export declare const button: string
export declare const buttons: string
export declare const bytelFooter: string
export declare const callToAction: string
export declare const card: string
export declare const cardContent: string
export declare const cardFooter: string
export declare const cardHeader: string
export declare const cardHeaderContent: string
export declare const cardHeaderIcon: string
export declare const cardHeaderTitle: string
export declare const cardImage: string
export declare const cardTitle: string
export declare const centimes: string
export declare const cents: string
export declare const chatContent: string
export declare const chatMessage: string
export declare const chatMessageAvatar: string
export declare const chatMessageContent: string
export declare const chatMessages: string
export declare const chatWindow: string
export declare const chatWindowInput: string
export declare const close: string
export declare const column: string
export declare const columns: string
export declare const container: string
export declare const control: string
export declare const count: string
export declare const countdown: string
export declare const description: string
export declare const details: string
export declare const disclaimer: string
export declare const disclaimerContent: string
export declare const disclaimerHeader: string
export declare const disclaimerItem: string
export declare const disclaimerMarker: string
export declare const dl: string
export declare const dot: string
export declare const dropdown: string
export declare const dropdownContent: string
export declare const dropdownDivider: string
export declare const dropdownItem: string
export declare const dropdownMenu: string
export declare const dropdownMenuList: string
export declare const dropdownTrigger: string
export declare const fa: string
export declare const field: string
export declare const fieldBody: string
export declare const fieldLabel: string
export declare const file: string
export declare const fileCta: string
export declare const fileIcon: string
export declare const fileInput: string
export declare const fileLabel: string
export declare const fileName: string
export declare const flexi4g: string
export declare const flexi4G4Gplus: string
export declare const flexi4g5g: string
export declare const flexi4g5gPlus: string
export declare const flexi4gPlus: string
export declare const flexi5g: string
export declare const flexiAccessibility: string
export declare const flexiAccomodation: string
export declare const flexiAddcalendarRdv: string
export declare const flexiAdvisor: string
export declare const flexiAfrica: string
export declare const flexiAirTravel: string
export declare const flexiArchiving: string
export declare const flexiArtificialIntelligence: string
export declare const flexiArtistChair: string
export declare const flexiAt: string
export declare const flexiAtCheckS: string
export declare const flexiAtCogsCircle: string
export declare const flexiAtExclamationCircle: string
export declare const flexiAtGlobe: string
export declare const flexiAtInfinityCircle: string
export declare const flexiAtInfo: string
export declare const flexiAtPlusCircle: string
export declare const flexiAtUnavailable: string
export declare const flexiAudioVisual: string
export declare const flexiAutoplan: string
export declare const flexiBabyphone: string
export declare const flexiBadges: string
export declare const flexiBall: string
export declare const flexiBank: string
export declare const flexiBarcodeSearch: string
export declare const flexiBattery: string
export declare const flexiBduo: string
export declare const flexiBeautician: string
export declare const flexiBellRinging: string
export declare const flexiBluetooth: string
export declare const flexiBox: string
export declare const flexiBox4g: string
export declare const flexiBoxAdd: string
export declare const flexiBoxCheckCircle: string
export declare const flexiBoxCheckCircleS: string
export declare const flexiBoxEole: string
export declare const flexiBoxExclamationCircle: string
export declare const flexiBoxFaq: string
export declare const flexiBoxInfoCircle: string
export declare const flexiBoxInfoCogs: string
export declare const flexiBoxMobile: string
export declare const flexiBoxRedo: string
export declare const flexiBoxSmartTv: string
export declare const flexiBoxStethoscope: string
export declare const flexiBoxUnavailable: string
export declare const flexiBtv: string
export declare const flexiBtvIllimite: string
export declare const flexiBtvplus: string
export declare const flexiBusinessTrip: string
export declare const flexiCalendar: string
export declare const flexiCalendarClockCircle: string
export declare const flexiCalendarCogsCircle: string
export declare const flexiCalendarExclamationCircle: string
export declare const flexiCalendarInfoCircle: string
export declare const flexiCalendarPlusCircle: string
export declare const flexiCalendarQuestionCircle: string
export declare const flexiCalendarUnavailable: string
export declare const flexiCamera: string
export declare const flexiCarPark: string
export declare const flexiCarpooling: string
export declare const flexiCarRent: string
export declare const flexiCatering: string
export declare const flexiCheck: string
export declare const flexiCheckCircle: string
export declare const flexiChildrenAccess: string
export declare const flexiChip: string
export declare const flexiClapperboard: string
export declare const flexiCleanSurface: string
export declare const flexiClickCollect2h: string
export declare const flexiClipboardChecklist: string
export declare const flexiClosed: string
export declare const flexiCloud: string
export declare const flexiCloud100go: string
export declare const flexiCloud20go: string
export declare const flexiCloud30go: string
export declare const flexiCloud50go: string
export declare const flexiCloud70go: string
export declare const flexiCloudCheck: string
export declare const flexiCloudCheckS: string
export declare const flexiCloudCogsCircle: string
export declare const flexiCloudExclamationCircle: string
export declare const flexiCloudGlobe: string
export declare const flexiCloudInfinity: string
export declare const flexiCloudPlusCircle: string
export declare const flexiCloudSave: string
export declare const flexiCo2Emission: string
export declare const flexiCogs: string
export declare const flexiCollaborativeLibrary: string
export declare const flexiComment: string
export declare const flexiCommentEarth: string
export declare const flexiCommentExclamationCircle: string
export declare const flexiCommentEye: string
export declare const flexiCommentQuestion: string
export declare const flexiCommentsQuestionDots: string
export declare const flexiCommentVoicemail: string
export declare const flexiCommunity: string
export declare const flexiConcierge: string
export declare const flexiContact: string
export declare const flexiContactlessPayment: string
export declare const flexiCorporateCard: string
export declare const flexiCourier: string
export declare const flexiCreditCard: string
export declare const flexiCreditCardAccepted: string
export declare const flexiCreditCardLock: string
export declare const flexiCreditCards: string
export declare const flexiCreditCards12: string
export declare const flexiCripplingDisease: string
export declare const flexiCse: string
export declare const flexiDesktop: string
export declare const flexiDiagnostic: string
export declare const flexiDistance: string
export declare const flexiDontTouch: string
export declare const flexiDuplicata: string
export declare const flexiEarSlash: string
export declare const flexiEarth: string
export declare const flexiEcoConception: string
export declare const flexiEcommerceProductReturn: string
export declare const flexiEcommercePromoLabel: string
export declare const flexiEcoresponsibleDigital: string
export declare const flexiElectricalOverload: string
export declare const flexiElectricalPlug: string
export declare const flexiElectricCar: string
export declare const flexiEnergy: string
export declare const flexiEnergyOptimization: string
export declare const flexiEnvelope: string
export declare const flexiEnvelopePlusCircle: string
export declare const flexiEnvironmentalFootprint: string
export declare const flexiEsim: string
export declare const flexiEthics: string
export declare const flexiEurope: string
export declare const flexiEuros: string
export declare const flexiExclamation: string
export declare const flexiExclamationCircle: string
export declare const flexiExclamationRedo: string
export declare const flexiExclamationTriangle: string
export declare const flexiFacemask1: string
export declare const flexiFacemask2: string
export declare const flexiFaciliti: string
export declare const flexiFileAttached: string
export declare const flexiFileEuro: string
export declare const flexiFileEuroCheckCircle: string
export declare const flexiFileEuroCheckCircleS: string
export declare const flexiFileEuroExclamationCircle: string
export declare const flexiFileEuroInfoCircle: string
export declare const flexiFileEuroLockCircle: string
export declare const flexiFileEuroQuestionCircle: string
export declare const flexiFileList: string
export declare const flexiFileManagement: string
export declare const flexiFileNew: string
export declare const flexiFilePdf: string
export declare const flexiFilm: string
export declare const flexiFingerprint: string
export declare const flexiFirstRuralArea: string
export declare const flexiFlashSell: string
export declare const flexiFlexymoovBicycle: string
export declare const flexiFlowerOrder: string
export declare const flexiFrance: string
export declare const flexiFranceMarker: string
export declare const flexiFrown: string
export declare const flexiGamepad: string
export declare const flexiGamesConsole: string
export declare const flexiGauge: string
export declare const flexiGaugeCogsCircle: string
export declare const flexiGaugeExclamationCircle: string
export declare const flexiGaugePlusCircle: string
export declare const flexiGift: string
export declare const flexiGoodPractices: string
export declare const flexiHairdresser: string
export declare const flexiHandicapzero: string
export declare const flexiHandMobile: string
export declare const flexiHandsfree: string
export declare const flexiHandsHelping: string
export declare const flexiHandTools: string
export declare const flexiHeadphones: string
export declare const flexiHeart: string
export declare const flexiHome: string
export declare const flexiHomeTools: string
export declare const flexiHotspot: string
export declare const flexiHourglass: string
export declare const flexiHydroGel: string
export declare const flexiIdentity: string
export declare const flexiImmersiveContentGlass: string
export declare const flexiImmersiveContentPeople: string
export declare const flexiInternalFraud: string
export declare const flexiIot: string
export declare const flexiIp: string
export declare const flexiLaFibre: string
export declare const flexiLaptop: string
export declare const flexiLaptopTabletMobile: string
export declare const flexiLightbulbOn: string
export declare const flexiLinesSpeed: string
export declare const flexiLink: string
export declare const flexiLinkCopy: string
export declare const flexiLock: string
export declare const flexiMail: string
export declare const flexiMailboxMarker: string
export declare const flexiMaker: string
export declare const flexiMapMarker: string
export declare const flexiMarker: string
export declare const flexiMassage: string
export declare const flexiMentalDisability: string
export declare const flexiMentalHandicap: string
export declare const flexiMicrowaves: string
export declare const flexiMobile: string
export declare const flexiMobile06Slash: string
export declare const flexiMobile07Slash: string
export declare const flexiMobile08Slash: string
export declare const flexiMobileBan: string
export declare const flexiMobileBroken: string
export declare const flexiMobileCloud: string
export declare const flexiMobileComment: string
export declare const flexiMobileEuro: string
export declare const flexiMobileEye: string
export declare const flexiMobileGlobe: string
export declare const flexiMobileHand: string
export declare const flexiMobileInfinity: string
export declare const flexiMobileLock: string
export declare const flexiMobilePercentage: string
export declare const flexiMobilePlusSimCards: string
export declare const flexiMobileReconditioned: string
export declare const flexiMobileRecovery: string
export declare const flexiMobileSync: string
export declare const flexiMobileTools: string
export declare const flexiMobileUpDown: string
export declare const flexiModem3g: string
export declare const flexiMotivation: string
export declare const flexiMouse: string
export declare const flexiMovingPersonsGoods: string
export declare const flexinessAsserted: string
export declare const flexinessRoot: string
export declare const flexiNetwork: string
export declare const flexiNetworkAntenna: string
export declare const flexiNewspapers: string
export declare const flexiNotebookTarifs: string
export declare const flexiNotes: string
export declare const flexiNotificationBottom: string
export declare const flexiNotificationTop: string
export declare const flexiOfficeSupply: string
export declare const flexiOptician: string
export declare const flexiPackagePreparation: string
export declare const flexiPaperclip: string
export declare const flexiParcel: string
export declare const flexiPause: string
export declare const flexiPaymentAmericanexpress: string
export declare const flexiPaymentCb: string
export declare const flexiPaymentMastercard: string
export declare const flexiPaymentPaypal: string
export declare const flexiPaymentVisa: string
export declare const flexiPersonDoor: string
export declare const flexiPhone: string
export declare const flexiPhoneAfrica: string
export declare const flexiPhoneBurger: string
export declare const flexiPhoneEuro: string
export declare const flexiPhoneEurope: string
export declare const flexiPhoneGlobe: string
export declare const flexiPhoneIncomingCall: string
export declare const flexiPhoneInfinity: string
export declare const flexiPhoneNotes: string
export declare const flexiPhoneOutgoingCall: string
export declare const flexiPhonePlusSimCard: string
export declare const flexiPhoneSwitzerland: string
export declare const flexiPhysicalDisability: string
export declare const flexiPictoFaciliti: string
export declare const flexiPictoHandicapzero: string
export declare const flexiPictoLaFibre: string
export declare const flexiPictoPaymentCb: string
export declare const flexiPictoPaymentMastercard: string
export declare const flexiPictoPaymentPaypal: string
export declare const flexiPictoPaymentVisa: string
export declare const flexiPlayBeginning: string
export declare const flexiPlayCircle: string
export declare const flexiPlexiExchange: string
export declare const flexiPlugCheck: string
export declare const flexiPlus: string
export declare const flexiPlusCircle: string
export declare const flexiPrinter: string
export declare const flexiPrintingStationery: string
export declare const flexiPriorityPath: string
export declare const flexiRecycle: string
export declare const flexiRedo: string
export declare const flexiRedo14Days: string
export declare const flexiRedo30Days: string
export declare const flexiRedo7Days: string
export declare const flexiReduceCo2Emission: string
export declare const flexiRemote: string
export declare const flexiRepeater: string
export declare const flexiRepeaterAlt: string
export declare const flexiRestrictedArea: string
export declare const flexiRingtoneWelcomeSound: string
export declare const flexiRotation360: string
export declare const flexiRules: string
export declare const flexiSamples: string
export declare const flexiSamplesCogsCircle: string
export declare const flexiSamplesExclamationMarkCircle: string
export declare const flexiSamplesPlusCircle: string
export declare const flexiSatelliteAntenna: string
export declare const flexiScan: string
export declare const flexiSdCard: string
export declare const flexiSearch: string
export declare const flexiSecurityHealth: string
export declare const flexiShield: string
export declare const flexiShieldAt: string
export declare const flexiShieldCheck: string
export declare const flexiShieldExclamation: string
export declare const flexiShieldPrivateLife: string
export declare const flexiShootingStar: string
export declare const flexiShoppingBag: string
export declare const flexiSimCard: string
export declare const flexiSimCardRedo: string
export declare const flexiSimCards: string
export declare const flexiSimCardUnlock: string
export declare const flexiSmile: string
export declare const flexiSmileNocircled: string
export declare const flexiSmilePlus: string
export declare const flexiSmsInfo: string
export declare const flexiSocialFacebook: string
export declare const flexiSocialInstagram: string
export declare const flexiSocialTwitter: string
export declare const flexiSocialYoutube: string
export declare const flexiSports: string
export declare const flexiSteeringWheel: string
export declare const flexiStopwatch: string
export declare const flexiStopwatch2h: string
export declare const flexiStopwatchClickCollect: string
export declare const flexiStopwatchClickCollect2h: string
export declare const flexiStore: string
export declare const flexiStoreLocator: string
export declare const flexiSunEuro: string
export declare const flexiSustainableDevelopment: string
export declare const flexiSync: string
export declare const flexiTablet: string
export declare const flexiTeamMeal: string
export declare const flexiTh: string
export declare const flexiThunderRedo: string
export declare const flexiTimes: string
export declare const flexiTimesCircle: string
export declare const flexiTools: string
export declare const flexiTopNews: string
export declare const flexiTrainingDiploma: string
export declare const flexiTransport: string
export declare const flexiTrash: string
export declare const flexiTravelAgency: string
export declare const flexiTravelPolicies: string
export declare const flexiTruck: string
export declare const flexiTruckSpeed: string
export declare const flexiTurkey: string
export declare const flexiTv: string
export declare const flexiTv4k: string
export declare const flexiTv8k: string
export declare const flexiTvBtv: string
export declare const flexiTvCurved: string
export declare const flexiTvHd: string
export declare const flexiTvInfinity: string
export declare const flexiTvMulti: string
export declare const flexiTvMultiOpticalFiber: string
export declare const flexiTvVod: string
export declare const flexiUiArrowDown: string
export declare const flexiUiArrowDownR: string
export declare const flexiUiArrowLeft: string
export declare const flexiUiArrowLeftR: string
export declare const flexiUiArrowRight: string
export declare const flexiUiArrowRightR: string
export declare const flexiUiArrowUp: string
export declare const flexiUiArrowUpR: string
export declare const flexiUiBell: string
export declare const flexiUiCheck: string
export declare const flexiUiCheckCircle: string
export declare const flexiUiCheckCircleS: string
export declare const flexiUiCheckR: string
export declare const flexiUiDownload: string
export declare const flexiUiEnvelope: string
export declare const flexiUiExclamation: string
export declare const flexiUiExclamationCircle: string
export declare const flexiUiExclamationCircleS: string
export declare const flexiUiExclamationR: string
export declare const flexiUiEye: string
export declare const flexiUiEyeS: string
export declare const flexiUiEyeSlash: string
export declare const flexiUiEyeSlashS: string
export declare const flexiUiHome: string
export declare const flexiUiInfo: string
export declare const flexiUiInfoCircle: string
export declare const flexiUiInfoCircleR: string
export declare const flexiUiLogo: string
export declare const flexiUiMarker: string
export declare const flexiUiMarkerS: string
export declare const flexiUiMenu: string
export declare const flexiUiMinus: string
export declare const flexiUiMinusCircle: string
export declare const flexiUiPauseS: string
export declare const flexiUiPencil: string
export declare const flexiUiPencilS: string
export declare const flexiUiPlayS: string
export declare const flexiUiPlus: string
export declare const flexiUiPlusCircle: string
export declare const flexiUiPlusCircleR: string
export declare const flexiUiPlusCircleS: string
export declare const flexiUiPlusR: string
export declare const flexiUiPower: string
export declare const flexiUiQuestion: string
export declare const flexiUiQuestionCircle: string
export declare const flexiUiQuestionCircleR: string
export declare const flexiUiRelaisColisExpress: string
export declare const flexiUiSearch: string
export declare const flexiUiSearchR: string
export declare const flexiUiShoppingBag: string
export declare const flexiUiShoppingCart: string
export declare const flexiUiSliders: string
export declare const flexiUiStar: string
export declare const flexiUiStarHalf: string
export declare const flexiUiStarS: string
export declare const flexiUiTimes: string
export declare const flexiUiTimesCircle: string
export declare const flexiUiTimesCircleR: string
export declare const flexiUiTimesCircleS: string
export declare const flexiUiTimesR: string
export declare const flexiUiTrash: string
export declare const flexiUiTrashS: string
export declare const flexiUiUpload: string
export declare const flexiUiUser: string
export declare const flexiUnavailable: string
export declare const flexiUnlimited: string
export declare const flexiUsbkey: string
export declare const flexiUser: string
export declare const flexiUserHeadset: string
export declare const flexiUsers: string
export declare const flexiUsersShieldS: string
export declare const flexiUsersShieldStarS: string
export declare const flexiUserTie: string
export declare const flexiVictory: string
export declare const flexiVisor: string
export declare const flexiVisuallyImpaired: string
export declare const flexiVoiceAssistance: string
export declare const flexiVoicemail: string
export declare const flexiVolumeOff: string
export declare const flexiVolumeOn: string
export declare const flexiVSign: string
export declare const flexiVtcTaxiMotorbike: string
export declare const flexiWall: string
export declare const flexiWasteReduction: string
export declare const flexiWatch: string
export declare const flexiWebcam: string
export declare const flexiWifi: string
export declare const flexiWifiLow: string
export declare const flexiWifiMedium: string
export declare const flexiWindow: string
export declare const flexiWorkplaceLayout: string
export declare const flexiWorkshop: string
export declare const footer: string
export declare const fromRight: string
export declare const fromTop: string
export declare const hasAddons: string
export declare const hasAddonsCentered: string
export declare const hasAddonsFullwidth: string
export declare const hasAddonsRight: string
export declare const hasArrowSeparator: string
export declare const hasBackground: string
export declare const hasBackgroundAdmin: string
export declare const hasBackgroundCobalt: string
export declare const hasBackgroundDanger: string
export declare const hasBackgroundDebug: string
export declare const hasBackgroundFlexGreen: string
export declare const hasBackgroundFlexOrange: string
export declare const hasBackgroundFlexPink: string
export declare const hasBackgroundFlexPurple: string
export declare const hasBackgroundGrey: string
export declare const hasBackgroundGreyDark: string
export declare const hasBackgroundGreyLight: string
export declare const hasBackgroundGreyLighter: string
export declare const hasBackgroundInfo: string
export declare const hasBackgroundPrimary: string
export declare const hasBackgroundQuaternary: string
export declare const hasBackgroundSecondary: string
export declare const hasBackgroundSuccess: string
export declare const hasBackgroundTertiary: string
export declare const hasBackgroundTertiaryDark: string
export declare const hasBackgroundTertiaryLight: string
export declare const hasBackgroundWarning: string
export declare const hasBackgroundWhite: string
export declare const hasBgGradient: string
export declare const hasBgImage: string
export declare const hasBody: string
export declare const hasBorderRadius: string
export declare const hasBorderRadiusLarge: string
export declare const hasBorderRadiusSmall: string
export declare const hasBulletSeparator: string
export declare const hasDescription: string
export declare const hasDotSeparator: string
export declare const hasDropdownArrow: string
export declare const hasDynamicPlaceholder: string
export declare const hasEndingArrow: string
export declare const hasFixedSize: string
export declare const hasHat: string
export declare const hasHatDesktop: string
export declare const hasHatMobile: string
export declare const hasHatTablet: string
export declare const hasIcon: string
export declare const hasIconLeft: string
export declare const hasIconRight: string
export declare const hasIconsLeft: string
export declare const hasIconsRight: string
export declare const hasInheritedColor: string
export declare const hasLongCta: string
export declare const hasMixins: string
export declare const hasName: string
export declare const hasOverlap: string
export declare const hasOverlay: string
export declare const hasPasswordDiscover: string
export declare const hasPatternLight: string
export declare const hasSlice: string
export declare const hasStatus: string
export declare const hasSucceedsSeparator: string
export declare const hasTextAdmin: string
export declare const hasTextAdminInvert: string
export declare const hasTextCentered: string
export declare const hasTextCenteredDesktop: string
export declare const hasTextCenteredDesktopOnly: string
export declare const hasTextCenteredFullhd: string
export declare const hasTextCenteredMobile: string
export declare const hasTextCenteredTablet: string
export declare const hasTextCenteredTabletOnly: string
export declare const hasTextCenteredTouch: string
export declare const hasTextCenteredWidescreen: string
export declare const hasTextCenteredWidescreenOnly: string
export declare const hasTextCobalt: string
export declare const hasTextCobaltInvert: string
export declare const hasTextDanger: string
export declare const hasTextDangerInvert: string
export declare const hasTextDebug: string
export declare const hasTextDebugInvert: string
export declare const hasTextFlexGreen: string
export declare const hasTextFlexGreenInvert: string
export declare const hasTextFlexOrange: string
export declare const hasTextFlexOrangeInvert: string
export declare const hasTextFlexPink: string
export declare const hasTextFlexPinkInvert: string
export declare const hasTextFlexPurple: string
export declare const hasTextFlexPurpleInvert: string
export declare const hasTextGrey: string
export declare const hasTextGreyDark: string
export declare const hasTextGreyLight: string
export declare const hasTextGreyLighter: string
export declare const hasTextInfo: string
export declare const hasTextInfoInvert: string
export declare const hasTextJustified: string
export declare const hasTextJustifiedDesktop: string
export declare const hasTextJustifiedDesktopOnly: string
export declare const hasTextJustifiedFullhd: string
export declare const hasTextJustifiedMobile: string
export declare const hasTextJustifiedTablet: string
export declare const hasTextJustifiedTabletOnly: string
export declare const hasTextJustifiedTouch: string
export declare const hasTextJustifiedWidescreen: string
export declare const hasTextJustifiedWidescreenOnly: string
export declare const hasTextLeft: string
export declare const hasTextLeftDesktop: string
export declare const hasTextLeftDesktopOnly: string
export declare const hasTextLeftFullhd: string
export declare const hasTextLeftMobile: string
export declare const hasTextLeftTablet: string
export declare const hasTextLeftTabletOnly: string
export declare const hasTextLeftTouch: string
export declare const hasTextLeftWidescreen: string
export declare const hasTextLeftWidescreenOnly: string
export declare const hasTextPrimary: string
export declare const hasTextPrimaryInvert: string
export declare const hasTextQuaternary: string
export declare const hasTextQuaternaryInvert: string
export declare const hasTextRight: string
export declare const hasTextRightDesktop: string
export declare const hasTextRightDesktopOnly: string
export declare const hasTextRightFullhd: string
export declare const hasTextRightMobile: string
export declare const hasTextRightTablet: string
export declare const hasTextRightTabletOnly: string
export declare const hasTextRightTouch: string
export declare const hasTextRightWidescreen: string
export declare const hasTextRightWidescreenOnly: string
export declare const hasTextSecondary: string
export declare const hasTextSecondaryInvert: string
export declare const hasTextSuccess: string
export declare const hasTextSuccessInvert: string
export declare const hasTextTertiary: string
export declare const hasTextTertiaryDark: string
export declare const hasTextTertiaryDarkInvert: string
export declare const hasTextTertiaryInvert: string
export declare const hasTextTertiaryLight: string
export declare const hasTextTertiaryLightInvert: string
export declare const hasTextWarning: string
export declare const hasTextWarningInvert: string
export declare const hasTextWeightBold: string
export declare const hasTextWeightExtrabold: string
export declare const hasTextWeightLight: string
export declare const hasTextWeightMedium: string
export declare const hasTextWeightNormal: string
export declare const hasTextWeightSemibold: string
export declare const hasTextWhite: string
export declare const hasTextWhiteInvert: string
export declare const hasVariant: string
export declare const hasWireframes: string
export declare const heading: string
export declare const help: string
export declare const hero: string
export declare const heroBack: string
export declare const heroBody: string
export declare const heroButtons: string
export declare const hoverColor: string
export declare const icon: string
export declare const iconAndText: string
export declare const iconList: string
export declare const image: string
export declare const imageListItemImg: string
export declare const imageListItemRoot: string
export declare const imageListItemStandard: string
export declare const imageListItemWoven: string
export declare const imageListMasonry: string
export declare const imageListRoot: string
export declare const important: string
export declare const input: string
export declare const inputDynamicPlaceholder: string
export declare const is0: string
export declare const is0Desktop: string
export declare const is0DesktopOnly: string
export declare const is0Fullhd: string
export declare const is0Mobile: string
export declare const is0Tablet: string
export declare const is0TabletOnly: string
export declare const is0Touch: string
export declare const is0Widescreen: string
export declare const is0WidescreenOnly: string
export declare const is1: string
export declare const is10: string
export declare const is10Desktop: string
export declare const is10DesktopOnly: string
export declare const is10Fullhd: string
export declare const is10Mobile: string
export declare const is10Tablet: string
export declare const is10TabletOnly: string
export declare const is10Touch: string
export declare const is10Widescreen: string
export declare const is10WidescreenOnly: string
export declare const is11: string
export declare const is11Desktop: string
export declare const is11DesktopOnly: string
export declare const is11Fullhd: string
export declare const is11Mobile: string
export declare const is11Tablet: string
export declare const is11TabletOnly: string
export declare const is11Touch: string
export declare const is11Widescreen: string
export declare const is11WidescreenOnly: string
export declare const is12: string
export declare const is128x128: string
export declare const is12Desktop: string
export declare const is12DesktopOnly: string
export declare const is12Fullhd: string
export declare const is12Mobile: string
export declare const is12Tablet: string
export declare const is12TabletOnly: string
export declare const is12Touch: string
export declare const is12Widescreen: string
export declare const is12WidescreenOnly: string
export declare const is16x16: string
export declare const is1Desktop: string
export declare const is1DesktopOnly: string
export declare const is1Fullhd: string
export declare const is1Mobile: string
export declare const is1Tablet: string
export declare const is1TabletOnly: string
export declare const is1Touch: string
export declare const is1Widescreen: string
export declare const is1WidescreenOnly: string
export declare const is2: string
export declare const is24x24: string
export declare const is2Desktop: string
export declare const is2DesktopOnly: string
export declare const is2Fullhd: string
export declare const is2Mobile: string
export declare const is2Tablet: string
export declare const is2TabletOnly: string
export declare const is2Touch: string
export declare const is2Widescreen: string
export declare const is2WidescreenOnly: string
export declare const is3: string
export declare const is32x32: string
export declare const is3Desktop: string
export declare const is3DesktopOnly: string
export declare const is3Fullhd: string
export declare const is3Mobile: string
export declare const is3Tablet: string
export declare const is3TabletOnly: string
export declare const is3Touch: string
export declare const is3Widescreen: string
export declare const is3WidescreenOnly: string
export declare const is4: string
export declare const is48x48: string
export declare const is4Desktop: string
export declare const is4DesktopOnly: string
export declare const is4Fullhd: string
export declare const is4Mobile: string
export declare const is4Tablet: string
export declare const is4TabletOnly: string
export declare const is4Touch: string
export declare const is4Widescreen: string
export declare const is4WidescreenOnly: string
export declare const is5: string
export declare const is5Desktop: string
export declare const is5DesktopOnly: string
export declare const is5Fullhd: string
export declare const is5Mobile: string
export declare const is5Tablet: string
export declare const is5TabletOnly: string
export declare const is5Touch: string
export declare const is5Widescreen: string
export declare const is5WidescreenOnly: string
export declare const is6: string
export declare const is64x64: string
export declare const is6Desktop: string
export declare const is6DesktopOnly: string
export declare const is6Fullhd: string
export declare const is6Mobile: string
export declare const is6Tablet: string
export declare const is6TabletOnly: string
export declare const is6Touch: string
export declare const is6Widescreen: string
export declare const is6WidescreenOnly: string
export declare const is7: string
export declare const is7Desktop: string
export declare const is7DesktopOnly: string
export declare const is7Fullhd: string
export declare const is7Mobile: string
export declare const is7Tablet: string
export declare const is7TabletOnly: string
export declare const is7Touch: string
export declare const is7Widescreen: string
export declare const is7WidescreenOnly: string
export declare const is8: string
export declare const is8Desktop: string
export declare const is8DesktopOnly: string
export declare const is8Fullhd: string
export declare const is8Mobile: string
export declare const is8Tablet: string
export declare const is8TabletOnly: string
export declare const is8Touch: string
export declare const is8Widescreen: string
export declare const is8WidescreenOnly: string
export declare const is9: string
export declare const is96x96: string
export declare const is9Desktop: string
export declare const is9DesktopOnly: string
export declare const is9Fullhd: string
export declare const is9Mobile: string
export declare const is9Tablet: string
export declare const is9TabletOnly: string
export declare const is9Touch: string
export declare const is9Widescreen: string
export declare const is9WidescreenOnly: string
export declare const isActive: string
export declare const isAdmin: string
export declare const isAlignContentBaseline: string
export declare const isAlignContentCenter: string
export declare const isAlignContentEnd: string
export declare const isAlignContentFlexEnd: string
export declare const isAlignContentFlexStart: string
export declare const isAlignContentSpaceAround: string
export declare const isAlignContentSpaceBetween: string
export declare const isAlignContentSpaceEvenly: string
export declare const isAlignContentStart: string
export declare const isAlignContentStretch: string
export declare const isAlignedEnd: string
export declare const isAlignItemsBaseline: string
export declare const isAlignItemsCenter: string
export declare const isAlignItemsEnd: string
export declare const isAlignItemsFlexEnd: string
export declare const isAlignItemsFlexStart: string
export declare const isAlignItemsSelfEnd: string
export declare const isAlignItemsSelfStart: string
export declare const isAlignItemsStart: string
export declare const isAlignItemsStretch: string
export declare const isAlignSelfAuto: string
export declare const isAlignSelfBaseline: string
export declare const isAlignSelfCenter: string
export declare const isAlignSelfFlexEnd: string
export declare const isAlignSelfFlexStart: string
export declare const isAlignSelfStretch: string
export declare const isAlternate: string
export declare const isAncestor: string
export declare const isAnimated: string
export declare const isArrowEnd: string
export declare const isArrowStart: string
export declare const isBanner: string
export declare const isBlock: string
export declare const isBlockDesktop: string
export declare const isBlockDesktopOnly: string
export declare const isBlockFullhd: string
export declare const isBlockMobile: string
export declare const isBlockTablet: string
export declare const isBlockTabletOnly: string
export declare const isBlockTouch: string
export declare const isBlockWidescreen: string
export declare const isBlockWidescreenOnly: string
export declare const isBodyHeader: string
export declare const isBordered: string
export declare const isBottom: string
export declare const isBottomRight: string
export declare const isBoxed: string
export declare const isBrief: string
export declare const isCapitalized: string
export declare const isCentered: string
export declare const isCenteredDesktop: string
export declare const isCenteredMobile: string
export declare const isCenteredTablet: string
export declare const isCheckradio: string
export declare const isChild: string
export declare const isCircled: string
export declare const isCircledAdmin: string
export declare const isCircledCobalt: string
export declare const isCircledDanger: string
export declare const isCircledDebug: string
export declare const isCircledFlexGreen: string
export declare const isCircledFlexOrange: string
export declare const isCircledFlexPink: string
export declare const isCircledFlexPurple: string
export declare const isCircledGrey: string
export declare const isCircledGreyDark: string
export declare const isCircledGreyLight: string
export declare const isCircledGreyLighter: string
export declare const isCircledInfo: string
export declare const isCircledPrimary: string
export declare const isCircledQuaternary: string
export declare const isCircledSecondary: string
export declare const isCircledSuccess: string
export declare const isCircledTertiary: string
export declare const isCircledTertiaryDark: string
export declare const isCircledTertiaryLight: string
export declare const isCircledWarning: string
export declare const isCircledWhite: string
export declare const isClearfix: string
export declare const isClipped: string
export declare const isClippedToBottom: string
export declare const isCobalt: string
export declare const isCompact: string
export declare const isComparative: string
export declare const isCurrent: string
export declare const isDanger: string
export declare const isDebug: string
export declare const isDescendant: string
export declare const isDescriptive: string
export declare const isDesktop: string
export declare const isDisabled: string
export declare const isDivider: string
export declare const isDone: string
export declare const isDownload: string
export declare const isElastic: string
export declare const isEmpty: string
export declare const isExpandable: string
export declare const isExpanded: string
export declare const isExpansion: string
export declare const isFirst: string
export declare const isFixed: string
export declare const isFlat: string
export declare const isFlatFlexGreen: string
export declare const isFlatFlexOrange: string
export declare const isFlatFlexPink: string
export declare const isFlatFlexPurple: string
export declare const isFlatPrimary: string
export declare const isFlatQuaternary: string
export declare const isFlatSecondary: string
export declare const isFlatTertiary: string
export declare const isFlex: string
export declare const isFlexDesktop: string
export declare const isFlexDesktopOnly: string
export declare const isFlexDirectionColumn: string
export declare const isFlexDirectionColumnReverse: string
export declare const isFlexDirectionRow: string
export declare const isFlexDirectionRowReverse: string
export declare const isFlexFullhd: string
export declare const isFlexGreen: string
export declare const isFlexGrow0: string
export declare const isFlexGrow1: string
export declare const isFlexGrow2: string
export declare const isFlexGrow3: string
export declare const isFlexGrow4: string
export declare const isFlexGrow5: string
export declare const isFlexible: string
export declare const isFlexMobile: string
export declare const isFlexOrange: string
export declare const isFlexPink: string
export declare const isFlexPurple: string
export declare const isFlexShrink0: string
export declare const isFlexShrink1: string
export declare const isFlexShrink2: string
export declare const isFlexShrink3: string
export declare const isFlexShrink4: string
export declare const isFlexShrink5: string
export declare const isFlexTablet: string
export declare const isFlexTabletOnly: string
export declare const isFlexTouch: string
export declare const isFlexWidescreen: string
export declare const isFlexWidescreenOnly: string
export declare const isFlexWrapNowrap: string
export declare const isFlexWrapWrap: string
export declare const isFlexWrapWrapReverse: string
export declare const isFloating: string
export declare const isFluid: string
export declare const isFocused: string
export declare const isFooterDesktop: string
export declare const isFooterMobile: string
export declare const isFooterSub: string
export declare const isFourFifths: string
export declare const isFourFifthsDesktop: string
export declare const isFourFifthsFullhd: string
export declare const isFourFifthsMobile: string
export declare const isFourFifthsTablet: string
export declare const isFourFifthsTouch: string
export declare const isFourFifthsWidescreen: string
export declare const isFourth: string
export declare const isFull: string
export declare const isFullDesktop: string
export declare const isFullFullhd: string
export declare const isFullhd: string
export declare const isFullheight: string
export declare const isFullMobile: string
export declare const isFullTablet: string
export declare const isFullTouch: string
export declare const isFullWidescreen: string
export declare const isFullwidth: string
export declare const isFullwidthMobile: string
export declare const isGap1: string
export declare const isGap2: string
export declare const isGap3: string
export declare const isGap4: string
export declare const isGap5: string
export declare const isGap6: string
export declare const isGap7: string
export declare const isGapless: string
export declare const isGrey: string
export declare const isGreyDark: string
export declare const isGreyLight: string
export declare const isGreyLighter: string
export declare const isGrouped: string
export declare const isGroupedCentered: string
export declare const isGroupedMultiline: string
export declare const isGroupedRight: string
export declare const isHalf: string
export declare const isHalfDesktop: string
export declare const isHalfFullhd: string
export declare const isHalfMobile: string
export declare const isHalfTablet: string
export declare const isHalfTouch: string
export declare const isHalfWidescreen: string
export declare const isHat: string
export declare const isHidden: string
export declare const isHiddenDesktop: string
export declare const isHiddenDesktopOnly: string
export declare const isHiddenFullhd: string
export declare const isHiddenMobile: string
export declare const isHiddenTablet: string
export declare const isHiddenTabletOnly: string
export declare const isHiddenTouch: string
export declare const isHiddenWidescreen: string
export declare const isHiddenWidescreenOnly: string
export declare const isHighlighted: string
export declare const isHorizontal: string
export declare const isHoverable: string
export declare const isHovered: string
export declare const isHuge: string
export declare const isIcon: string
export declare const isIllustratedMobile: string
export declare const isImage: string
export declare const isIncluded: string
export declare const isInfo: string
export declare const isInline: string
export declare const isInlineBlock: string
export declare const isInlineBlockDesktop: string
export declare const isInlineBlockDesktopOnly: string
export declare const isInlineBlockFullhd: string
export declare const isInlineBlockMobile: string
export declare const isInlineBlockTablet: string
export declare const isInlineBlockTabletOnly: string
export declare const isInlineBlockTouch: string
export declare const isInlineBlockWidescreen: string
export declare const isInlineBlockWidescreenOnly: string
export declare const isInlined: string
export declare const isInlineDesktop: string
export declare const isInlineDesktopOnly: string
export declare const isInlineFlex: string
export declare const isInlineFlexDesktop: string
export declare const isInlineFlexDesktopOnly: string
export declare const isInlineFlexFullhd: string
export declare const isInlineFlexMobile: string
export declare const isInlineFlexTablet: string
export declare const isInlineFlexTabletOnly: string
export declare const isInlineFlexTouch: string
export declare const isInlineFlexWidescreen: string
export declare const isInlineFlexWidescreenOnly: string
export declare const isInlineFullhd: string
export declare const isInlineMobile: string
export declare const isInlineTablet: string
export declare const isInlineTabletOnly: string
export declare const isInlineTouch: string
export declare const isInlineWidescreen: string
export declare const isInlineWidescreenOnly: string
export declare const isInstit: string
export declare const isInverted: string
export declare const isInvertedMobile: string
export declare const isInvisible: string
export declare const isInvisibleDesktop: string
export declare const isInvisibleDesktopOnly: string
export declare const isInvisibleFullhd: string
export declare const isInvisibleMobile: string
export declare const isInvisibleTablet: string
export declare const isInvisibleTabletOnly: string
export declare const isInvisibleTouch: string
export declare const isInvisibleWidescreen: string
export declare const isInvisibleWidescreenOnly: string
export declare const isItalic: string
export declare const isJustifiedCenter: string
export declare const isJustifiedCenterDesktop: string
export declare const isJustifiedCenterDesktopOnly: string
export declare const isJustifiedCenterFullhd: string
export declare const isJustifiedCenterMobile: string
export declare const isJustifiedCenterTablet: string
export declare const isJustifiedCenterTabletOnly: string
export declare const isJustifiedCenterTouch: string
export declare const isJustifiedCenterWidescreen: string
export declare const isJustifiedCenterWidescreenOnly: string
export declare const isJustifiedEnd: string
export declare const isJustifiedEndDesktop: string
export declare const isJustifiedEndDesktopOnly: string
export declare const isJustifiedEndFullhd: string
export declare const isJustifiedEndMobile: string
export declare const isJustifiedEndTablet: string
export declare const isJustifiedEndTabletOnly: string
export declare const isJustifiedEndTouch: string
export declare const isJustifiedEndWidescreen: string
export declare const isJustifiedEndWidescreenOnly: string
export declare const isJustifiedStart: string
export declare const isJustifiedStartDesktop: string
export declare const isJustifiedStartDesktopOnly: string
export declare const isJustifiedStartFullhd: string
export declare const isJustifiedStartMobile: string
export declare const isJustifiedStartTablet: string
export declare const isJustifiedStartTabletOnly: string
export declare const isJustifiedStartTouch: string
export declare const isJustifiedStartWidescreen: string
export declare const isJustifiedStartWidescreenOnly: string
export declare const isJustifyContentCenter: string
export declare const isJustifyContentEnd: string
export declare const isJustifyContentFlexEnd: string
export declare const isJustifyContentFlexStart: string
export declare const isJustifyContentLeft: string
export declare const isJustifyContentRight: string
export declare const isJustifyContentSpaceAround: string
export declare const isJustifyContentSpaceBetween: string
export declare const isJustifyContentSpaceEvenly: string
export declare const isJustifyContentStart: string
export declare const isLarge: string
export declare const isLeft: string
export declare const isLevel: string
export declare const isLoaded: string
export declare const isLoading: string
export declare const isLong: string
export declare const isLowercase: string
export declare const isMainPrice: string
export declare const isMarginless: string
export declare const isMaxDesktop: string
export declare const isMaxWidescreen: string
export declare const isMe: string
export declare const isMedium: string
export declare const isMegadropdownParent: string
export declare const isMobile: string
export declare const isMotionlessDesktop: string
export declare const isMultiline: string
export declare const isMultiple: string
export declare const isMutuallyExclusive: string
export declare const isNarrow: string
export declare const isNarrowDesktop: string
export declare const isNarrowFullhd: string
export declare const isNarrowMobile: string
export declare const isNarrowTablet: string
export declare const isNarrowTouch: string
export declare const isNarrowWidescreen: string
export declare const isNew: string
export declare const isNormal: string
export declare const isNowrap: string
export declare const isNpm: string
export declare const isOffset1: string
export declare const isOffset10: string
export declare const isOffset10Desktop: string
export declare const isOffset10Fullhd: string
export declare const isOffset10Mobile: string
export declare const isOffset10Tablet: string
export declare const isOffset10Touch: string
export declare const isOffset10Widescreen: string
export declare const isOffset11: string
export declare const isOffset11Desktop: string
export declare const isOffset11Fullhd: string
export declare const isOffset11Mobile: string
export declare const isOffset11Tablet: string
export declare const isOffset11Touch: string
export declare const isOffset11Widescreen: string
export declare const isOffset12: string
export declare const isOffset12Desktop: string
export declare const isOffset12Fullhd: string
export declare const isOffset12Mobile: string
export declare const isOffset12Tablet: string
export declare const isOffset12Touch: string
export declare const isOffset12Widescreen: string
export declare const isOffset1Desktop: string
export declare const isOffset1Fullhd: string
export declare const isOffset1Mobile: string
export declare const isOffset1Tablet: string
export declare const isOffset1Touch: string
export declare const isOffset1Widescreen: string
export declare const isOffset2: string
export declare const isOffset2Desktop: string
export declare const isOffset2Fullhd: string
export declare const isOffset2Mobile: string
export declare const isOffset2Tablet: string
export declare const isOffset2Touch: string
export declare const isOffset2Widescreen: string
export declare const isOffset3: string
export declare const isOffset3Desktop: string
export declare const isOffset3Fullhd: string
export declare const isOffset3Mobile: string
export declare const isOffset3Tablet: string
export declare const isOffset3Touch: string
export declare const isOffset3Widescreen: string
export declare const isOffset4: string
export declare const isOffset4Desktop: string
export declare const isOffset4Fullhd: string
export declare const isOffset4Mobile: string
export declare const isOffset4Tablet: string
export declare const isOffset4Touch: string
export declare const isOffset4Widescreen: string
export declare const isOffset5: string
export declare const isOffset5Desktop: string
export declare const isOffset5Fullhd: string
export declare const isOffset5Mobile: string
export declare const isOffset5Tablet: string
export declare const isOffset5Touch: string
export declare const isOffset5Widescreen: string
export declare const isOffset6: string
export declare const isOffset6Desktop: string
export declare const isOffset6Fullhd: string
export declare const isOffset6Mobile: string
export declare const isOffset6Tablet: string
export declare const isOffset6Touch: string
export declare const isOffset6Widescreen: string
export declare const isOffset7: string
export declare const isOffset7Desktop: string
export declare const isOffset7Fullhd: string
export declare const isOffset7Mobile: string
export declare const isOffset7Tablet: string
export declare const isOffset7Touch: string
export declare const isOffset7Widescreen: string
export declare const isOffset8: string
export declare const isOffset8Desktop: string
export declare const isOffset8Fullhd: string
export declare const isOffset8Mobile: string
export declare const isOffset8Tablet: string
export declare const isOffset8Touch: string
export declare const isOffset8Widescreen: string
export declare const isOffset9: string
export declare const isOffset9Desktop: string
export declare const isOffset9Fullhd: string
export declare const isOffset9Mobile: string
export declare const isOffset9Tablet: string
export declare const isOffset9Touch: string
export declare const isOffset9Widescreen: string
export declare const isOffsetFourFifths: string
export declare const isOffsetFourFifthsDesktop: string
export declare const isOffsetFourFifthsFullhd: string
export declare const isOffsetFourFifthsMobile: string
export declare const isOffsetFourFifthsTablet: string
export declare const isOffsetFourFifthsTouch: string
export declare const isOffsetFourFifthsWidescreen: string
export declare const isOffsetHalf: string
export declare const isOffsetHalfDesktop: string
export declare const isOffsetHalfFullhd: string
export declare const isOffsetHalfMobile: string
export declare const isOffsetHalfTablet: string
export declare const isOffsetHalfTouch: string
export declare const isOffsetHalfWidescreen: string
export declare const isOffsetOneFifth: string
export declare const isOffsetOneFifthDesktop: string
export declare const isOffsetOneFifthFullhd: string
export declare const isOffsetOneFifthMobile: string
export declare const isOffsetOneFifthTablet: string
export declare const isOffsetOneFifthTouch: string
export declare const isOffsetOneFifthWidescreen: string
export declare const isOffsetOneQuarter: string
export declare const isOffsetOneQuarterDesktop: string
export declare const isOffsetOneQuarterFullhd: string
export declare const isOffsetOneQuarterMobile: string
export declare const isOffsetOneQuarterTablet: string
export declare const isOffsetOneQuarterTouch: string
export declare const isOffsetOneQuarterWidescreen: string
export declare const isOffsetOneThird: string
export declare const isOffsetOneThirdDesktop: string
export declare const isOffsetOneThirdFullhd: string
export declare const isOffsetOneThirdMobile: string
export declare const isOffsetOneThirdTablet: string
export declare const isOffsetOneThirdTouch: string
export declare const isOffsetOneThirdWidescreen: string
export declare const isOffsetThreeFifths: string
export declare const isOffsetThreeFifthsDesktop: string
export declare const isOffsetThreeFifthsFullhd: string
export declare const isOffsetThreeFifthsMobile: string
export declare const isOffsetThreeFifthsTablet: string
export declare const isOffsetThreeFifthsTouch: string
export declare const isOffsetThreeFifthsWidescreen: string
export declare const isOffsetThreeQuarters: string
export declare const isOffsetThreeQuartersDesktop: string
export declare const isOffsetThreeQuartersFullhd: string
export declare const isOffsetThreeQuartersMobile: string
export declare const isOffsetThreeQuartersTablet: string
export declare const isOffsetThreeQuartersTouch: string
export declare const isOffsetThreeQuartersWidescreen: string
export declare const isOffsetTwoFifths: string
export declare const isOffsetTwoFifthsDesktop: string
export declare const isOffsetTwoFifthsFullhd: string
export declare const isOffsetTwoFifthsMobile: string
export declare const isOffsetTwoFifthsTablet: string
export declare const isOffsetTwoFifthsTouch: string
export declare const isOffsetTwoFifthsWidescreen: string
export declare const isOffsetTwoThirds: string
export declare const isOffsetTwoThirdsDesktop: string
export declare const isOffsetTwoThirdsFullhd: string
export declare const isOffsetTwoThirdsMobile: string
export declare const isOffsetTwoThirdsTablet: string
export declare const isOffsetTwoThirdsTouch: string
export declare const isOffsetTwoThirdsWidescreen: string
export declare const isOneFifth: string
export declare const isOneFifthDesktop: string
export declare const isOneFifthFullhd: string
export declare const isOneFifthMobile: string
export declare const isOneFifthTablet: string
export declare const isOneFifthTouch: string
export declare const isOneFifthWidescreen: string
export declare const isOneQuarter: string
export declare const isOneQuarterDesktop: string
export declare const isOneQuarterFullhd: string
export declare const isOneQuarterMobile: string
export declare const isOneQuarterTablet: string
export declare const isOneQuarterTouch: string
export declare const isOneQuarterWidescreen: string
export declare const isOneThird: string
export declare const isOneThirdDesktop: string
export declare const isOneThirdFullhd: string
export declare const isOneThirdMobile: string
export declare const isOneThirdTablet: string
export declare const isOneThirdTouch: string
export declare const isOneThirdWidescreen: string
export declare const isOutlined: string
export declare const isOverlapped: string
export declare const isOverlay: string
export declare const isPaddingless: string
export declare const isParent: string
export declare const isPartner: string
export declare const isPlain: string
export declare const isPolyfilled: string
export declare const isPopoverActive: string
export declare const isPopoverBottom: string
export declare const isPopoverLeft: string
export declare const isPopoverRight: string
export declare const isPrimary: string
export declare const isPulledLeft: string
export declare const isPulledRight: string
export declare const isQuaternary: string
export declare const isRadiusless: string
export declare const isReversed: string
export declare const isRight: string
export declare const isRightAligned: string
export declare const isRounded: string
export declare const isRtl: string
export declare const isScrollable: string
export declare const isSearching: string
export declare const isSecond: string
export declare const isSecondary: string
export declare const isSectionTitle: string
export declare const isSelected: string
export declare const isSelectLine: string
export declare const isShadowless: string
export declare const isShort: string
export declare const isSidebarMenu: string
export declare const isSize1: string
export declare const isSize1Desktop: string
export declare const isSize1Fullhd: string
export declare const isSize1Mobile: string
export declare const isSize1Tablet: string
export declare const isSize1Touch: string
export declare const isSize1Widescreen: string
export declare const isSize2: string
export declare const isSize2Desktop: string
export declare const isSize2Fullhd: string
export declare const isSize2Mobile: string
export declare const isSize2Tablet: string
export declare const isSize2Touch: string
export declare const isSize2Widescreen: string
export declare const isSize3: string
export declare const isSize3Desktop: string
export declare const isSize3Fullhd: string
export declare const isSize3Mobile: string
export declare const isSize3Tablet: string
export declare const isSize3Touch: string
export declare const isSize3Widescreen: string
export declare const isSize4: string
export declare const isSize4Desktop: string
export declare const isSize4Fullhd: string
export declare const isSize4Mobile: string
export declare const isSize4Tablet: string
export declare const isSize4Touch: string
export declare const isSize4Widescreen: string
export declare const isSize5: string
export declare const isSize5Desktop: string
export declare const isSize5Fullhd: string
export declare const isSize5Mobile: string
export declare const isSize5Tablet: string
export declare const isSize5Touch: string
export declare const isSize5Widescreen: string
export declare const isSize6: string
export declare const isSize6Desktop: string
export declare const isSize6Fullhd: string
export declare const isSize6Mobile: string
export declare const isSize6Tablet: string
export declare const isSize6Touch: string
export declare const isSize6Widescreen: string
export declare const isSize7: string
export declare const isSize7Desktop: string
export declare const isSize7Fullhd: string
export declare const isSize7Mobile: string
export declare const isSize7Tablet: string
export declare const isSize7Touch: string
export declare const isSize7Widescreen: string
export declare const isSize8: string
export declare const isSize8Desktop: string
export declare const isSize8Fullhd: string
export declare const isSize8Mobile: string
export declare const isSize8Tablet: string
export declare const isSize8Touch: string
export declare const isSize8Widescreen: string
export declare const isSmall: string
export declare const isSmallMobile: string
export declare const isSpaced: string
export declare const isSpecial: string
export declare const isStacked: string
export declare const isStackedDesktop: string
export declare const isStackedMobile: string
export declare const isStackedTablet: string
export declare const isStackedWidescreen: string
export declare const isStatic: string
export declare const isSticky: string
export declare const isStretched: string
export declare const isStriked: string
export declare const isStriped: string
export declare const isStrong: string
export declare const isSuccess: string
export declare const isSwitch: string
export declare const isTertiary: string
export declare const isTertiaryDark: string
export declare const isTertiaryLight: string
export declare const isText: string
export declare const isThick: string
export declare const isThreeFifths: string
export declare const isThreeFifthsDesktop: string
export declare const isThreeFifthsFullhd: string
export declare const isThreeFifthsMobile: string
export declare const isThreeFifthsTablet: string
export declare const isThreeFifthsTouch: string
export declare const isThreeFifthsWidescreen: string
export declare const isThreeQuarters: string
export declare const isThreeQuartersDesktop: string
export declare const isThreeQuartersFullhd: string
export declare const isThreeQuartersMobile: string
export declare const isThreeQuartersTablet: string
export declare const isThreeQuartersTouch: string
export declare const isThreeQuartersWidescreen: string
export declare const isTooltipActive: string
export declare const isTop: string
export declare const isTransparent: string
export declare const isTransparentOnly: string
export declare const isTwoFifths: string
export declare const isTwoFifthsDesktop: string
export declare const isTwoFifthsFullhd: string
export declare const isTwoFifthsMobile: string
export declare const isTwoFifthsTablet: string
export declare const isTwoFifthsTouch: string
export declare const isTwoFifthsWidescreen: string
export declare const isTwoThirds: string
export declare const isTwoThirdsDesktop: string
export declare const isTwoThirdsFullhd: string
export declare const isTwoThirdsMobile: string
export declare const isTwoThirdsTablet: string
export declare const isTwoThirdsTouch: string
export declare const isTwoThirdsWidescreen: string
export declare const isUnavailable: string
export declare const isUnboxed: string
export declare const isUnderline: string
export declare const isUnselectable: string
export declare const isUp: string
export declare const isUppercase: string
export declare const isVariable: string
export declare const isVcentered: string
export declare const isVcenteredDesktop: string
export declare const isVcenteredMobile: string
export declare const isVcenteredTablet: string
export declare const isVertical: string
export declare const isVerticalMobile: string
export declare const isVeryLong: string
export declare const isVeryShort: string
export declare const isVolumeControl: string
export declare const isWaiting: string
export declare const isWarning: string
export declare const isWhite: string
export declare const isWidescreen: string
export declare const isWireframe: string
export declare const isWrapped: string
export declare const knob: string
export declare const label: string
export declare const level: string
export declare const levelItem: string
export declare const levelLeft: string
export declare const levelRight: string
export declare const link: string
export declare const loader: string
export declare const loadingPulse: string
export declare const login: string
export declare const logo: string
export declare const main: string
export declare const mainContent: string
export declare const media: string
export declare const mention: string
export declare const menu: string
export declare const menuClose: string
export declare const menuLabel: string
export declare const menuList: string
export declare const menuOpen: string
export declare const menuTitle: string
export declare const modal: string
export declare const modalBackground: string
export declare const modalClose: string
export declare const modalContent: string
export declare const modalTitle: string
export declare const navbar: string
export declare const navbarBrand: string
export declare const navbarCategoryTitle: string
export declare const navbarDivider: string
export declare const navbarDropdown: string
export declare const navbarDropdownClose: string
export declare const navbarDropdownSection: string
export declare const navbarEnd: string
export declare const navbarExtras: string
export declare const navbarHeader: string
export declare const navbarIcons: string
export declare const navbarItem: string
export declare const navbarItemAccordion: string
export declare const navbarItemAccordionBack: string
export declare const navbarItemAccordionContent: string
export declare const navbarItemAccordionHeader: string
export declare const navbarItemAccordionTitle: string
export declare const navbarLink: string
export declare const navbarLinks: string
export declare const navbarMenu: string
export declare const navbarStart: string
export declare const navbarTitle: string
export declare const none: string
export declare const notification: string
export declare const notifications: string
export declare const number: string
export declare const options: string
export declare const pagination: string
export declare const paginationEllipsis: string
export declare const paginationLink: string
export declare const paginationList: string
export declare const paginationNext: string
export declare const paginationPrevious: string
export declare const paragraph: string
export declare const partnersIcons: string
export declare const patternDark: string
export declare const period: string
export declare const periode: string
export declare const pie: string
export declare const placeHolderShimmer: string
export declare const planCallToAction: string
export declare const planFooter: string
export declare const planHeader: string
export declare const planItem: string
export declare const planItemDetails: string
export declare const planItems: string
export declare const planItemTitle: string
export declare const planPrice: string
export declare const planSticker: string
export declare const plusSymbol: string
export declare const popover: string
export declare const popoverContent: string
export declare const popoverTrigger: string
export declare const price: string
export declare const priceDetails: string
export declare const pricingPlan: string
export declare const pricingPlanExtra: string
export declare const pricingPlanProduct: string
export declare const pricingTable: string
export declare const pricingTableExtra: string
export declare const productTour: string
export declare const productTourTargetActive: string
export declare const progress: string
export declare const progress0: string
export declare const progress1: string
export declare const progress10: string
export declare const progress100: string
export declare const progress11: string
export declare const progress12: string
export declare const progress13: string
export declare const progress14: string
export declare const progress15: string
export declare const progress16: string
export declare const progress17: string
export declare const progress18: string
export declare const progress19: string
export declare const progress2: string
export declare const progress20: string
export declare const progress21: string
export declare const progress22: string
export declare const progress23: string
export declare const progress24: string
export declare const progress25: string
export declare const progress26: string
export declare const progress27: string
export declare const progress28: string
export declare const progress29: string
export declare const progress3: string
export declare const progress30: string
export declare const progress31: string
export declare const progress32: string
export declare const progress33: string
export declare const progress34: string
export declare const progress35: string
export declare const progress36: string
export declare const progress37: string
export declare const progress38: string
export declare const progress39: string
export declare const progress4: string
export declare const progress40: string
export declare const progress41: string
export declare const progress42: string
export declare const progress43: string
export declare const progress44: string
export declare const progress45: string
export declare const progress46: string
export declare const progress47: string
export declare const progress48: string
export declare const progress49: string
export declare const progress5: string
export declare const progress50: string
export declare const progress51: string
export declare const progress52: string
export declare const progress53: string
export declare const progress54: string
export declare const progress55: string
export declare const progress56: string
export declare const progress57: string
export declare const progress58: string
export declare const progress59: string
export declare const progress6: string
export declare const progress60: string
export declare const progress61: string
export declare const progress62: string
export declare const progress63: string
export declare const progress64: string
export declare const progress65: string
export declare const progress66: string
export declare const progress67: string
export declare const progress68: string
export declare const progress69: string
export declare const progress7: string
export declare const progress70: string
export declare const progress71: string
export declare const progress72: string
export declare const progress73: string
export declare const progress74: string
export declare const progress75: string
export declare const progress76: string
export declare const progress77: string
export declare const progress78: string
export declare const progress79: string
export declare const progress8: string
export declare const progress80: string
export declare const progress81: string
export declare const progress82: string
export declare const progress83: string
export declare const progress84: string
export declare const progress85: string
export declare const progress86: string
export declare const progress87: string
export declare const progress88: string
export declare const progress89: string
export declare const progress9: string
export declare const progress90: string
export declare const progress91: string
export declare const progress92: string
export declare const progress93: string
export declare const progress94: string
export declare const progress95: string
export declare const progress96: string
export declare const progress97: string
export declare const progress98: string
export declare const progress99: string
export declare const progressBar: string
export declare const progressCircle: string
export declare const progressCircleBackgroundEmpty: string
export declare const progressCircleBackgroundSecondary: string
export declare const progressCircleBackgroundTertiary: string
export declare const progressCircleBackgroundWarning: string
export declare const progressCircleContent: string
export declare const progressCircleSlice: string
export declare const progressCircleSub: string
export declare const progressCircleTitle: string
export declare const radialProgressBar: string
export declare const radialProgressBars: string
export declare const reactAutosuggestContainer: string
export declare const row: string
export declare const rows: string
export declare const searchAutocomplete: string
export declare const searchAutosuggest: string
export declare const searchBar: string
export declare const searchModal: string
export declare const searchNoModal: string
export declare const searchResults: string
export declare const section: string
export declare const select: string
export declare const showMore: string
export declare const slice: string
export declare const sliceBody: string
export declare const sliceCallToAction: string
export declare const sliceContent: string
export declare const sliceGroup: string
export declare const sliceIcon: string
export declare const sliceImage: string
export declare const slices: string
export declare const sliceSelect: string
export declare const sliderDot: string
export declare const slidingLink: string
export declare const small: string
export declare const socialIcons: string
export declare const specification: string
export declare const spinAround: string
export declare const step: string
export declare const stepper: string
export declare const sticker: string
export declare const subFooter: string
export declare const subfooterLink: string
export declare const subfooterTitle: string
export declare const subtable: string
export declare const subtitle: string
export declare const suptitle: string
export declare const table: string
export declare const tableContainer: string
export declare const tabs: string
export declare const tag: string
export declare const tags: string
export declare const text: string
export declare const textarea: string
export declare const tile: string
export declare const tilesContainer: string
export declare const timeline: string
export declare const timelineContent: string
export declare const timelineHeader: string
export declare const timelineItem: string
export declare const timelineMarker: string
export declare const title: string
export declare const toggle: string
export declare const toolbar: string
export declare const toolbarGroup: string
export declare const toolbarItem: string
export declare const toolbarRow: string
export declare const toolbarSpace: string
export declare const tooltip: string
export declare const useGrid: string
export declare const user: string
export declare const userMenu: string
export declare const value: string
export declare const wave: string
export declare const withArrow: string
export declare const wrapper: string
