export declare const animateFromRight: string
export declare const animateFromTop: string
export declare const flexinessRoot: string
export declare const fromRight: string
export declare const fromTop: string
export declare const is1: string
export declare const is10: string
export declare const is10Mobile: string
export declare const is11: string
export declare const is11Mobile: string
export declare const is12: string
export declare const is12Mobile: string
export declare const is1Mobile: string
export declare const is2: string
export declare const is2Mobile: string
export declare const is3: string
export declare const is3Mobile: string
export declare const is4: string
export declare const is4Mobile: string
export declare const is5: string
export declare const is5Mobile: string
export declare const is6: string
export declare const is6Mobile: string
export declare const is7: string
export declare const is7Mobile: string
export declare const is8: string
export declare const is8Mobile: string
export declare const is9: string
export declare const is9Mobile: string
export declare const isAncestor: string
export declare const isChild: string
export declare const isMultiline: string
export declare const isParent: string
export declare const isVertical: string
export declare const isVerticalMobile: string
export declare const placeHolderShimmer: string
export declare const spinAround: string
export declare const tile: string
