import {
  CognitoIdentityProviderClient,
  AdminAddUserToGroupCommand,
  GetGroupCommand,
  CreateGroupCommand
} from '@aws-sdk/client-cognito-identity-provider';
import type { PostConfirmationTriggerHandler } from 'aws-lambda';

const cognitoClient = new CognitoIdentityProviderClient();

export const handler: PostConfirmationTriggerHandler = async (event) => {
  const groupName = process.env.GROUP_NAME || 'v4onBoardSignUpGroup';

  const groupParams = {
    GroupName: groupName,
    UserPoolId: event.userPoolId,
  };

  const addUserParams = {
    GroupName: groupName,
    UserPoolId: event.userPoolId,
    Username: event.userName,
  };

  try {
    // Check if the group exists; if it doesn't, create it.
    try {
      await cognitoClient.send(new GetGroupCommand(groupParams));
    } catch (error) {
      // Group doesn't exist, create it
      await cognitoClient.send(new CreateGroupCommand({
        ...groupParams,
        Description: 'Autogenerated group for user registration'
      }));
    }

    // Add the user to the group
    await cognitoClient.send(new AdminAddUserToGroupCommand(addUserParams));

    console.log(`User ${event.userName} added to group ${groupName}`);
  } catch (error) {
    console.error('Error adding user to group:', error);
    throw error;
  }

  return event;
};
