export declare const animateFromRight: string
export declare const animateFromTop: string
export declare const button: string
export declare const container: string
export declare const flexinessRoot: string
export declare const fromRight: string
export declare const fromTop: string
export declare const hasBackground: string
export declare const hasMixins: string
export declare const hero: string
export declare const heroBack: string
export declare const heroBody: string
export declare const heroButtons: string
export declare const isCentered: string
export declare const isInfo: string
export declare const isInstit: string
export declare const isLarge: string
export declare const isMedium: string
export declare const isOverlapped: string
export declare const isPrimary: string
export declare const isSmall: string
export declare const paragraph: string
export declare const patternDark: string
export declare const placeHolderShimmer: string
export declare const section: string
export declare const spinAround: string
export declare const subtitle: string
export declare const suptitle: string
export declare const tag: string
export declare const title: string
