export declare const animateFromRight: string
export declare const animateFromTop: string
export declare const container: string
export declare const flexinessRoot: string
export declare const fromRight: string
export declare const fromTop: string
export declare const hasMixins: string
export declare const hasOverlap: string
export declare const hasOverlay: string
export declare const hasPatternLight: string
export declare const isInfo: string
export declare const isInverted: string
export declare const isLarge: string
export declare const isMedium: string
export declare const isSmall: string
export declare const isTransparentOnly: string
export declare const patternDark: string
export declare const placeHolderShimmer: string
export declare const section: string
export declare const spinAround: string
