const poets: string[] = [
  'François Villon',
  'Joachim du Bellay',
  'Pierre de Ronsard',
  'Jean de La Fontaine',
  'Voltaire',
  'Alphonse de Lamartine',
  'Victor Hugo',
  'Charles Baudelaire',
  'Paul Verlaine',
  'Arthur Rimbaud',
  'Stéphane Mallarmé',
  'Guillaume Apollinaire',
  'Paul Valéry',
  'Jacques Prévert',
  'Clément Marot',
  'Théodore de Banville',
  'Gérard de Nerval',
  'Marceline Desbordes-Valmore',
  'Jules Laforgue',
  'René Char',
  'Louis Aragon',
  'Jean Cocteau',
  'Aimé Césaire',
  'Francis Ponge',
  'William Shakespeare',
  'John Milton',
  'Alexander Pope',
  'William Blake',
  'William Wordsworth',
  'Samuel Taylor Coleridge',
  'Lord Byron',
  'Percy Bysshe Shelley',
  'John Keats',
  'Lord Alfred Tennyson',
  'Robert Browning',
  'Elizabeth Barrett Browning',
  'Gerard Manley Hopkins',
  'Thomas Hardy',
  'Rudyard Kipling',
  'Wilfred Owen',
  'Siegfried Sassoon',
  'T.S. Eliot',
  'W. B. Yeats',
  'Dylan Thomas',
  'Philip Larkin',
  'Ted Hughes',
  'Sylvia Plath',
  'Seamus Heaney',
]

export { poets }
