export declare const animateFromRight: string
export declare const animateFromTop: string
export declare const container: string
export declare const flexinessRoot: string
export declare const fromRight: string
export declare const fromTop: string
export declare const isFluid: string
export declare const isFullhd: string
export declare const isFullwidth: string
export declare const isMaxDesktop: string
export declare const isMaxWidescreen: string
export declare const isMedium: string
export declare const isWidescreen: string
export declare const navbar: string
export declare const placeHolderShimmer: string
export declare const spinAround: string
