export declare const animateFromRight: string
export declare const animateFromTop: string
export declare const button: string
export declare const control: string
export declare const dropdownTrigger: string
export declare const fa: string
export declare const field: string
export declare const fieldBody: string
export declare const fieldLabel: string
export declare const file: string
export declare const fileCta: string
export declare const fileIcon: string
export declare const fileInput: string
export declare const fileLabel: string
export declare const fileName: string
export declare const flexinessRoot: string
export declare const fromRight: string
export declare const fromTop: string
export declare const hasAddons: string
export declare const hasAddonsCentered: string
export declare const hasAddonsFullwidth: string
export declare const hasAddonsRight: string
export declare const hasDynamicPlaceholder: string
export declare const hasIcon: string
export declare const hasIconRight: string
export declare const hasIconsLeft: string
export declare const hasIconsRight: string
export declare const hasName: string
export declare const hasPasswordDiscover: string
export declare const help: string
export declare const icon: string
export declare const input: string
export declare const isActive: string
export declare const isAdmin: string
export declare const isBoxed: string
export declare const isCentered: string
export declare const isCobalt: string
export declare const isDanger: string
export declare const isDebug: string
export declare const isEmpty: string
export declare const isExpanded: string
export declare const isFlexGreen: string
export declare const isFlexOrange: string
export declare const isFlexPink: string
export declare const isFlexPurple: string
export declare const isFocused: string
export declare const isFullwidth: string
export declare const isGrouped: string
export declare const isGroupedCentered: string
export declare const isGroupedMultiline: string
export declare const isGroupedRight: string
export declare const isHorizontal: string
export declare const isHovered: string
export declare const isInfo: string
export declare const isLarge: string
export declare const isLoading: string
export declare const isLong: string
export declare const isMedium: string
export declare const isMobile: string
export declare const isNarrow: string
export declare const isNormal: string
export declare const isPrimary: string
export declare const isQuaternary: string
export declare const isRight: string
export declare const isSearch: string
export declare const isSearching: string
export declare const isSecondary: string
export declare const isShort: string
export declare const isSmall: string
export declare const isSuccess: string
export declare const isTertiary: string
export declare const isTertiaryDark: string
export declare const isTertiaryLight: string
export declare const isVeryLong: string
export declare const isVeryShort: string
export declare const isWarning: string
export declare const isWhite: string
export declare const label: string
export declare const placeHolderShimmer: string
export declare const select: string
export declare const spinAround: string
