export declare const animateFromRight: string
export declare const animateFromTop: string
export declare const bLazy: string
export declare const bLoaded: string
export declare const flexinessRoot: string
export declare const fromRight: string
export declare const fromTop: string
export declare const hasBgGradient: string
export declare const hasBgImage: string
export declare const image: string
export declare const imageListItemImg: string
export declare const imageListItemRoot: string
export declare const imageListItemStandard: string
export declare const imageListItemWoven: string
export declare const imageListMasonry: string
export declare const imageListRoot: string
export declare const placeHolderShimmer: string
export declare const spinAround: string
