export declare const animateFromRight: string
export declare const animateFromTop: string
export declare const field: string
export declare const flexinessRoot: string
export declare const fromRight: string
export declare const fromTop: string
export declare const isInverted: string
export declare const options: string
export declare const placeHolderShimmer: string
export declare const spinAround: string
export declare const useGrid: string
