export declare const animateFromRight: string
export declare const animateFromTop: string
export declare const block: string
export declare const flexinessRoot: string
export declare const fromRight: string
export declare const fromTop: string
export declare const heading: string
export declare const isLarge: string
export declare const isMedium: string
export declare const isSmall: string
export declare const loader: string
export declare const number: string
export declare const placeHolderShimmer: string
export declare const spinAround: string
