export declare const animateFromRight: string
export declare const animateFromTop: string
export declare const flexinessRoot: string
export declare const fromRight: string
export declare const fromTop: string
export declare const hasInheritedColor: string
export declare const is1: string
export declare const is2: string
export declare const is3: string
export declare const is4: string
export declare const isAdmin: string
export declare const isFlexPurple: string
export declare const isInverted: string
export declare const isNowrap: string
export declare const isPlain: string
export declare const isStatic: string
export declare const isWrapped: string
export declare const link: string
export declare const paragraph: string
export declare const placeHolderShimmer: string
export declare const slidingLink: string
export declare const spinAround: string
export declare const text: string
