export declare const animateFromRight: string
export declare const animateFromTop: string
export declare const flexinessRoot: string
export declare const fromRight: string
export declare const fromTop: string
export declare const isActive: string
export declare const isAdmin: string
export declare const isCobalt: string
export declare const isDanger: string
export declare const isDebug: string
export declare const isDisabled: string
export declare const isFlexGreen: string
export declare const isFlexOrange: string
export declare const isFlexPink: string
export declare const isFlexPurple: string
export declare const isFocused: string
export declare const isFullwidth: string
export declare const isHovered: string
export declare const isInfo: string
export declare const isLarge: string
export declare const isLoading: string
export declare const isMedium: string
export declare const isMultiple: string
export declare const isPrimary: string
export declare const isQuaternary: string
export declare const isRounded: string
export declare const isSecondary: string
export declare const isSmall: string
export declare const isSuccess: string
export declare const isTertiary: string
export declare const isTertiaryDark: string
export declare const isTertiaryLight: string
export declare const isWarning: string
export declare const isWhite: string
export declare const placeHolderShimmer: string
export declare const select: string
export declare const spinAround: string
