export declare const animateFromRight: string
export declare const animateFromTop: string
export declare const flexinessRoot: string
export declare const fromRight: string
export declare const fromTop: string
export declare const hasHat: string
export declare const hasHatDesktop: string
export declare const hasHatMobile: string
export declare const hasHatTablet: string
export declare const isAdmin: string
export declare const isCobalt: string
export declare const isDanger: string
export declare const isDebug: string
export declare const isFlexGreen: string
export declare const isFlexOrange: string
export declare const isFlexPink: string
export declare const isFlexPurple: string
export declare const isFullheight: string
export declare const isHat: string
export declare const isInfo: string
export declare const isInverted: string
export declare const isOutlined: string
export declare const isPrimary: string
export declare const isQuaternary: string
export declare const isSecondary: string
export declare const isSmall: string
export declare const isStretched: string
export declare const isSuccess: string
export declare const isTertiary: string
export declare const isTertiaryDark: string
export declare const isTertiaryLight: string
export declare const isWarning: string
export declare const isWhite: string
export declare const placeHolderShimmer: string
export declare const spinAround: string
export declare const sticker: string
