export declare const animateFromRight: string
export declare const animateFromTop: string
export declare const box: string
export declare const flexinessRoot: string
export declare const fromRight: string
export declare const fromTop: string
export declare const isAdmin: string
export declare const isBodyHeader: string
export declare const isBordered: string
export declare const isCobalt: string
export declare const isCompact: string
export declare const isComparative: string
export declare const isDanger: string
export declare const isDebug: string
export declare const isExpandable: string
export declare const isExpanded: string
export declare const isExpansion: string
export declare const isFlexGreen: string
export declare const isFlexOrange: string
export declare const isFlexPink: string
export declare const isFlexPurple: string
export declare const isFullwidth: string
export declare const isHoverable: string
export declare const isInfo: string
export declare const isLarge: string
export declare const isNarrow: string
export declare const isPrimary: string
export declare const isQuaternary: string
export declare const isSecondary: string
export declare const isSelected: string
export declare const isStriped: string
export declare const isSuccess: string
export declare const isTertiary: string
export declare const isTertiaryDark: string
export declare const isTertiaryLight: string
export declare const isVcentered: string
export declare const isWarning: string
export declare const isWhite: string
export declare const placeHolderShimmer: string
export declare const spinAround: string
export declare const subtable: string
export declare const table: string
export declare const tableContainer: string
export declare const toggle: string
